<div id="content" class="container">

	<div class="row">
	
		
		<div class="span5 box_color ">
	
			<div class="margem">
				<h3>Vantagens</h3>
				
				<p>
				
					Esta é a seção do plano na qual você apresenta um breve resumo da organização da sua empresa ou negócio, sua história, 
					seu status atual e suas projeções futuras para pesquisa e desenvolvimento, se for o caso. Enfatize as características 
					únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. Dê uma idéia do que você espera conseguir 
					em três ou cinco anos. A descrição legal da empresa deve conter o seguinte: Esta é a seção do plano na qual você apresenta 
					um breve resumo da organização da sua empresa ou negócio, sua história, seu status atual e suas projeções futuras para pesquisa e 
					desenvolvimento, se for o caso. Enfatize as características únicas de seu produto ou serviço e , diga como você pode beneficiar o 
					cliente. Dê uma idéia do que você espera conseguir em três ou cinco anos. A descrição legal da empresa deve conter o seguinte: 
					Esta é a seção do plano na qual você apresenta um breve resumo da organização da sua empresa ou negócio, sua história, seu status 
					atual e suas projeções futuras para pesquisa e desenvolvimento, se for o caso. Enfatize as características únicas de seu produto ou 
					serviço e , diga como você pode beneficiar o cliente. 
					Dê uma idéia do que você espera conseguir em três ou cinco anos. A descrição legal da empresa deve conter o seguinte:
				
				</p>
			
			</div>
		
		</div>
		
		<div class="span6 offset1 box_color ">
	
			<div class="margem">
				<h3>Portal do Cliente</h3>
				
				<form class="form-vertical " id="contact-form" action="/contato" method="post">
					
					<label for="Contact_name" class="required"><b>Usuário</b></label>
					<!--<input class="span3" name="Contact[name]" id="Contact_name" type="text" style="width:310px">-->
					<input class="span5" name="Contact[name]" id="Contact_name" type="text">
					<span class="help-block error" id="Contact_name_em_" style="display: none"></span>
					
					<label for="Contact_name" class="required"><b>Senha</b></label>
					<!--<input class="span3" name="Contact[name]" id="Contact_name" type="text" style="width:310px">-->
					<input class="span5" name="Contact[name]" id="Contact_name" type="text">
					<span class="help-block error" id="Contact_name_em_" style="display: none"></span>
					
					<label class="checkbox">
					  <input type="checkbox"> Mantenha-me Conectado
					</label>
					
					<div class="form-actions" style="margin-bottom:10px">
						<input class="btn btn-primary" type="submit" name="yt1" value="Enviar">            
						<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
					</div>
					
				</form>
			
			</div>
		
		</div>
	
	
	</div>
</div>