<?php echo $this->partial('application/partials/banner_princ'); ?>

<div id="main-nav-tabs" style="margin-top:-10px" class="hidden-phone">
	<div class="container">
		<div class="search-categories" style="width:119%">
			<form class="form-vertical " method="GET">
				<div class="row-fluid">
					<div class="filtro_select" style="padding-left:0">
						<select class="span12" name="" id="">
							<option value="">Tipo de Leilão</option>
							<option value="outros">Outros</option>
						</select>    
					</div>
					<div class="filtro_select">
						<select class="span12" disabled="disabled" name="Search[subcategory]" id="Search_subcategory">
							<option value="">Estado</option>
						</select>    
					</div>
					<div class="filtro_select">
						<select class="span12" name="" id="">
						<option value="">Cidade</option>
						</select>    
					</div>

					<div class="filtro_select">
						<select class="span12" disabled="disabled" name="" id="">
						<option value="">Bairro</option>
						</select>    
					</div>
					
					<div class="filtro_select">
						<select class="span12" disabled="disabled" name="" id="">
						<option value="">Valor</option>
						</select>    
					</div>

					<div class="filtro_select" style="margin-top:13px;">
					<button class="btn btn-block btn-primary" type="submit" id=""><i class="icon-white icon-search" style="font-size: 14px;"></i> Filtrar</button>
					</div>
				</div>
				
				<div class="row-fluid">
					<div class="filtro_select" style="padding-left:0">
						<select class="span12" name="Search[category]" id="Search_category">
							<option value="">Status do Leilao</option>
							<option value="outros">Outros</option>
						</select>    
					</div>
					<div class="filtro_select">
						<select class="span12" name="Search[state]" id="Search_state">
						<option value="">Produto</option>
						</select>    
					</div>

					<div class="filtro_select">
						<select class="span12" disabled="disabled" name="Search[city]" id="Search_city">
						<option value="">Categoria</option>
						</select>    
					</div>
					
					<div class="filtro_select">
						<select class="span12" disabled="disabled" name="" id="">
						<option value="">Bairro</option>
						</select>    
					</div>
					
					<div class="filtro_select">
						<select class="span12" disabled="disabled" name="" id="">
						<option value="">Data</option>
						</select>    
					</div>
				
				</div>

			</form>
		</div>
	</div>
</div>


<div id="main-nav-tabs" class="visible-phone">
	<div class="container">
		<div id="sti">
			<div class="tab-content">
				<div id="sti_tab_1" class="tab-pane fade active in">
					<div class="search-categories " style="">
						<form class="form-vertical " id="search-simple-form" action="/search/index" method="GET">
							<div class="row-fluid">
								<div class="span2">
									<select class="span12" name="Search[category]" id="Search_category">
										<option value="">Tipo de Leilão</option>
										<option value="outros">Outros</option>
									</select>    
								</div>
								<div class="span2">
									<select class="span12" disabled="disabled" name="Search[subcategory]" id="Search_subcategory">
										<option value="">Estado</option>
									</select>    
								</div>
								<div class="span2">
									<select class="span12" name="Search[state]" id="Search_state">
									<option value="">Cidade</option>
									</select>    
								</div>

								<div class="span2">
									<select class="span12" disabled="disabled" name="Search[city]" id="Search_city">
									<option value="">Bairro</option>
									</select>    
								</div>
								
								<div class="span2">
									<select class="span12" name="Search[category]" id="Search_category">
										<option value="">Status do Leilao</option>
										<option value="outros">Outros</option>
									</select>    
								</div>
								<div class="span2">
									<select class="span12" name="Search[state]" id="Search_state">
									<option value="">Produto</option>
									</select>    
								</div>

								<div class="span2">
									<select class="span12" disabled="disabled" name="Search[city]" id="Search_city">
									<option value="">Categoria</option>
									</select>    
								</div>
								
								<div class="span2">
									<select class="span12" disabled="disabled" name="Search[city]" id="Search_city">
									<option value="">Sub Categoria</option>
									</select>    
								</div>
								
								<div class="span2">
									<select class="span12" disabled="disabled" name="Search[city]" id="Search_city">
									<option value="">Valor</option>
									</select>    
								</div>
								
								<div class="span2">
									<select class="span12" disabled="disabled" name="Search[city]" id="Search_city">
									<option value="">Data</option>
									</select>    
								</div>

								<div class="span2" style="margin-top:20px">
								<button class="btn btn-block btn-primary" type="submit" id="fast-search"><i class="icon-white icon-search" style="font-size: 14px;"></i> Filtrar</button>
								</div>
							</div>

						</form>
					</div>
				</div>
			</div>
		</div> 
	</div>
</div>

<div id="content" class="container">

	<div class="cards-list-alt" id="batches-list">

		<div class="top">

			<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

			<div class="pagination">
				<ul id="yw1" class="yiiPager">
					<li class="first disabled"><a href="/">&lt;&lt;</a></li>
					<li class="previous disabled"><a href="/">&lt;</a></li>
					<li class="num active"><a href="/">1</a></li>
					<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
					<li class="num"><a href="/?pagina=3">3</a></li>
					<li class="num"><a href="/?pagina=4">4</a></li>
					<li class="num"><a href="/?pagina=5">5</a></li>
					<li class="num"><a href="/?pagina=6">6</a></li>
					<li class="num"><a href="/?pagina=7">7</a></li>
					<li class="num"><a href="/?pagina=8">8</a></li>
					<li class="num"><a href="/?pagina=9">9</a></li>
					<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
					<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
				</ul>
			</div>

		</div>

		<?php echo $this->partial('application/partials/card_leilao'); ?>
		<?php echo $this->partial('application/partials/card_leilao'); ?>
		<?php echo $this->partial('application/partials/card_leilao'); ?>
		<?php echo $this->partial('application/partials/card_leilao'); ?>
	
		<div class="top">

			<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

			<div class="pagination">
				<ul id="yw1" class="yiiPager">
					<li class="first disabled"><a href="/">&lt;&lt;</a></li>
					<li class="previous disabled"><a href="/">&lt;</a></li>
					<li class="num active"><a href="/">1</a></li>
					<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
					<li class="num"><a href="/?pagina=3">3</a></li>
					<li class="num"><a href="/?pagina=4">4</a></li>
					<li class="num"><a href="/?pagina=5">5</a></li>
					<li class="num"><a href="/?pagina=6">6</a></li>
					<li class="num"><a href="/?pagina=7">7</a></li>
					<li class="num"><a href="/?pagina=8">8</a></li>
					<li class="num"><a href="/?pagina=9">9</a></li>
					<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
					<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
				</ul>
			</div>

		</div>

	</div>


	<?php echo $this->partial('application/partials/pesquisa_rapida'); ?>

</div>



