<?php
$this->adminMenu()->setActiveItemId('gerenciarLoja');
$this->headLink()->prependStylesheet($this->basePath('css/bootstrap-table.min.css'));
?>

<div id='msg_sucesso' class="alert alert-success alert-dismissible text-center" style="display:none">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></button>
</div>

<div id='msg_erro' class="alert alert-danger alert-dismissible text-center" style="display:none">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></button>
</div>

<section class="content-header">
  <h1>
	Criar Loja
  </h1>
</section>

<section class="content">

	<?= $this->form()->openTag($form); ?>
	
		<?= $this->formElement($form->get('cd_loja')); ?>

	<div class="row">
	
		<div class="col-md-6">
		
			<div class="box box-primary">
				
				<div class="box-body">
					<div class="form-group">
						<?= $this->formLabel($form->get('nm_loja')); ?>
						<?= $this->formElement($form->get('nm_loja')); ?>
					</div>
					<div class="form-group">
						<?= $this->formLabel($form->get('desc_atua_loja')); ?>
						<?= $this->formElement($form->get('desc_atua_loja')); ?>
					</div>		
					
					<div class="form-group">
						<?= $this->formLabel($form->get('cd_cidade')); ?>
						<?= $this->formElement($form->get('cd_cidade')); ?>
					</div>	
				
					<div class="row">
						<div class="col-md-6">
							
							<div class="form-group">
								<?= $this->formLabel($form->get('nr_tel_fixo')); ?>

								<div class="input-group">
									<div class="input-group-addon"><i class="fa fa-phone"></i></div>
									<?= $this->formElement($form->get('nr_tel_fixo')); ?>
								</div>
							</div>
																					
						</div>
						
						<div class="col-md-6">
							
							<div class="form-group">
								<?= $this->formLabel($form->get('nr_tel_whats')); ?>

								<div class="input-group">
									<div class="input-group-addon"><i class="fa fa-phone"></i></div>
									<?= $this->formElement($form->get('nr_tel_whats')); ?>
								</div>
							</div>
							
						</div>
					</div>
											
					<div class="form-group">
						<div class="row">
							<?= $this->formLabel($form->get('link_facebook')); ?>
							<div class="col-md-10">
								<?= $this->formElement($form->get('link_facebook')); ?>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<div class="row">
							<?= $this->formLabel($form->get('link_instagram')); ?>
							<div class="col-md-10">
								<?= $this->formElement($form->get('link_instagram')); ?>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<div class="row">
							<?= $this->formLabel($form->get('link_google_plus')); ?>
							<div class="col-md-10">
								<?= $this->formElement($form->get('link_google_plus')); ?>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<div class="row">
							<?= $this->formLabel($form->get('link_you_tube')); ?>
							<div class="col-md-10">
								<?= $this->formElement($form->get('link_you_tube')); ?>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<div class="row">
							<?= $this->formLabel($form->get('link_pinterest')); ?>
							<div class="col-md-10">
								<?= $this->formElement($form->get('link_pinterest')); ?>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<div class="row">
							<?= $this->formLabel($form->get('link_twitter')); ?>
							<div class="col-md-10">
								<?= $this->formElement($form->get('link_twitter')); ?>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-md-6">
							
							<div class="form-group">
								<?= $this->formLabel($form->get('desc_email')); ?>
								<?= $this->formElement($form->get('desc_email')); ?>
							</div>
							
						</div>
						
						<div class="col-md-6">
							
							<div class="form-group">	
								<?= $this->formLabel($form->get('end_email')); ?>
								<?= $this->formElement($form->get('end_email')); ?>
							</div>
							
						</div>
					</div>
					
					<div class="form-group">
					
						<button id='add_email' type="button" class="btn btn-primary"><i class="fa fa-plus"></i></button>
						<button id='remove_email' type="button" class="btn btn-primary"><i class="fa fa-minus"></i></button>
					
					</div>
					
					<div class="form-group">									
						<table id="table_email" class="table table-hover">
						</table>
					</div>
				
				</div>				
			</div>

		</div>
		
		<div class="col-md-6">
			<div class="box box-primary">
			
				<div class="box-body">
					
					<div class="form-group">
						<?= $this->formLabel($form->get('desc_empresa_loja')); ?>
						<?= $this->formElement($form->get('desc_empresa_loja')); ?>
					</div>
					
					<div class="form-group">
						<?= $this->formLabel($form->get('desc_missao_loja')); ?>
						<?= $this->formElement($form->get('desc_missao_loja')); ?>
					</div>
					
					<div class="form-group">
						<?= $this->formLabel($form->get('desc_visao_loja')); ?>
						<?= $this->formElement($form->get('desc_visao_loja')); ?>
					</div>
					
					<div class="form-group">
						<?= $this->formLabel($form->get('desc_valor_loja')); ?>
						<?= $this->formElement($form->get('desc_valor_loja')); ?>
					</div>
					
					<div class="form-group">
					
						<button id='add_ciade' type="button" class="btn btn-primary"><i class="fa fa-plus"></i></button>
						<button id='remove_cidade' type="button" class="btn btn-primary"><i class="fa fa-minus"></i></button>
					
					</div>
					
					<div class="form-group">									
						<table id="table_cidade" class="table table-hover">
						</table>
					</div>
				
				</div>
			
			</div>
			
			<!--<div class="box box-primary">
			
				<div class="box-header with-border">
				  <h3 class="box-title">Endereço</h3>
				</div>
			
				<div class="box-body">
						
					<div class="form-group">
						<label for="cep_loja">Cep</label>
						<input type="text" name="cep_loja" id="cep_loja" maxlength="8" class="form-control" placeholder="Cep" value="">
					</div>
					
					<div class="form-group">								
						<label for="cidade">Estado</label>
						<select class="form-control">
						
							<option>Selecione um Estado</option>
						
						</select>
					</div>
					
					<div class="form-group">								
						<label for="cidade">Cidade</label>
						<select class="form-control">
						
							<option>Selecione uma cidade</option>
						
						</select>
					</div>
					
					<div class="row">
						<div class="col-md-6">
							
							<div class="form-group">
								<label for="cep_loja">Bairro</label>
								<input type="text" name="cep_loja" id="cep_loja" maxlength="8" class="form-control" placeholder="Cep" value="">
							</div>
							
						</div>
						
						<div class="col-md-6">
							
							<div class="form-group">
								<label for="cep_loja">Numero</label>
								<input type="text" name="cep_loja" id="cep_loja" maxlength="8" class="form-control" placeholder="Cep" value="">
							</div>
							
						</div>
					</div>
					
					<div class="row">
						<div class="col-md-6">
							
							<div class="form-group">
								<label for="cep_loja">Logradouro</label>
								<input type="text" name="cep_loja" id="cep_loja" maxlength="8" class="form-control" placeholder="Cep" value="">
							</div>
							
						</div>
						
						<div class="col-md-6">
							
							<div class="form-group">
								<label for="cep_loja">Complemento</label>
								<input type="text" name="cep_loja" id="cep_loja" maxlength="8" class="form-control" placeholder="Cep" value="">
							</div>
							
						</div>
					</div>
					
				</div>
			
			</div>-->
		</div>

	</div>
	
	<div class="row">
	
		<div class="col-md-12 text-center">
				
			<div class="box">
				<div class="box-body">
					<button id="btn_incluir" type="submit" class="btn btn-primary">Incluir</button>
					<button id="btn_alterar" type="submit" class="btn btn-warning" disabled>Alterar</button>
					<button id="btn_excluir" type="button" class="btn btn-danger" disabled>Excluir</button>
					<button id="btn_limpar" type="button" class="btn btn-info">Limpar</button>
				</div>
			</div>
		
		</div>
	
	</div>
	
	<section class="content-header">
	  <h1>
		Lojas Cadastradas
	  </h1>
	</section>
	
	<div class="row">
	
		<div class="col-md-12">
				
			<div class="box">
				<div class="box-body">
					<table id="table_listagem" class="table table-hover" >
						<!--<thead>
							<tr>
								<th data-field="cdGpr" data-visible="false"></th>
								<th data-field="nmGpr">Nome</th>
								<th data-field="descAtuaGpr">Descrição</th>
							</tr>
						</thead>-->
					</table>
				</div>
			</div>
		
		</div>
	
	</div>	
	
	<?= $this->form()->closeTag(); ?>

</section>

</div>

<?php

$this->headScript()->appendFile($this->basePath('js/bootstrap-table.min.js'), 'text/javascript');
$this->headScript()->appendFile($this->basePath('js/bootstrap-table-pt-BR.min.js'), 'text/javascript');
$this->headScript()->appendFile($this->basePath('adminlte/plugins/input-mask/jquery.inputmask.js'), 'text/javascript');
//$this->headScript()->appendFile($this->basePath('js/dropify.min.js'), 'text/javascript');
$this->headScript()->appendFile($this->basePath('js/sgs/loja/gerenciar.js'), 'text/javascript');

?>