<?=$this->headLink()->setStylesheet('css/application/home.css');?>
<?=$this->headScript()->prependFile('js/application/home.js');?>

<div style="margin-bottom: 20px;" class="hidden-phone carousel slide" id="main-carousel">
	<ol class="carousel-indicators">
		<li data-target="#main-carousel" data-slide-to="0" class=""></li>
		<li data-target="#main-carousel" data-slide-to="1" class=""></li>
		<li data-target="#main-carousel" data-slide-to="2" class=""></li>	
		<li data-target="#main-carousel" data-slide-to="3" class=""></li>
		<li data-target="#main-carousel" data-slide-to="4" class=""></li>
		<li data-target="#main-carousel" data-slide-to="5" class=""></li>
		<li data-target="#main-carousel" data-slide-to="6" class=""></li>
		<li data-target="#main-carousel" data-slide-to="7" class="active"></li>
		<li data-target="#main-carousel" data-slide-to="8" class=""></li>
		<li data-target="#main-carousel" data-slide-to="9" class=""></li>
		<li data-target="#main-carousel" data-slide-to="10" class=""></li>
		<li data-target="#main-carousel" data-slide-to="11" class=""></li>
	</ol>
	<div class="carousel-inner">
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/ML07124">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/bd062d822072d8d72f6f8dbd620ee130_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - IMÓVEIS SANTANDER - EX-AGÊNCIAS">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/ML07110">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/bae9f8543ed0585521ca7a1172217495_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - BRICKELL 06 LOTES">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/imoveis/mt/imovel-rural-11917-ha-nova-olimpia-mt-j15192">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/3786992f9aa78a1fd42e8b9e51c55717_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - IMÓVEL RURAL 11.917 HA">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/imoveis/sp/imovel-comercial-ex-agencia-1232-m2-sao-bernardo-do-campo-sp-x16365">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/b96e6e9c46a0d83f87388c6320a6132f_1170x250.jpg"
				alt="LEILÃO SANTANDER - IMÓVEL COMERCIAL (EX-AGÊNCIA) 1.232 m² - SBC - SP">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/imoveis/sp/terreno-16391-m2-guarulhos-sp-j15896">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/385d89b97b10e41a59bf07dafddd749a_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - TERRENO 16.391 m²">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/ML07102">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/65ac5202f191e54027aa9a7a0d4774b5_1170x250.jpg" 
				alt="Leilão de Imóveis Comerciais - BRL Trust Investimentos">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/ML07102">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/65fc1c7b08affb542d3c1d82c84bec38_1170x250.jpg" 
				alt="Leilão de Imóveis Comerciais - BRL Trust Investimentos LOTES 08 E 10">
			</a>
		</div>
		<div width="1170" height="250" class="item active">
			<a href="https://www.megaleiloes.com.br/imoveis/sp/casa-326-m2-alphaville-residencial-10-santana-de-parnaiba-sp-j15899">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/2ccca05777aabf479e8d9693e0e44d79_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - CASA 326 m² - SANTANA DE PARNAÍBA - SP">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/imoveis/sp/terreno-18388-m2-jardim-maria-estela-sao-paulo-sp-j15017">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/64611bc9921f0a9ca6ee6e4a5ab5eba1_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - TERRENO 18.388 m²">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/ML07134">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/4b21c62b5bd03893246dfcb9e666a08e_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - ZANINI">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/ML07105">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/932fc7c7059336d6a13dc2329fa41abf_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - BANCO ITAÚ 10 LOTES">
			</a>
		</div>
		<div width="1170" height="250" class="item">
			<a href="https://www.megaleiloes.com.br/imoveis/sp/area-de-terras-58717-m2-z-15-campinas-sp-x16148">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/c8fd81def5af98aff6bafe6a68609832_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - ÁREA DE TERRAS 58.181 m²">
			</a>
		</div>
	</div>

	<a class="carousel-control left" href="#main-carousel" data-slide="prev">‹</a>
	<a class="carousel-control right" href="#main-carousel" data-slide="next">›</a>

</div>

<div class="cards-list-alt" id="batches-list">

	<div class="top">
	
		<div><h3>Leilões Judiciais</h3></div>
		
		<hr class="divisão_hr">

		<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

		<div class="pagination">
			<ul id="yw1" class="yiiPager">
				<li class="first disabled"><a href="/">&lt;&lt;</a></li>
				<li class="previous disabled"><a href="/">&lt;</a></li>
				<li class="num active"><a href="/">1</a></li>
				<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
				<li class="num"><a href="/?pagina=3">3</a></li>
				<li class="num"><a href="/?pagina=4">4</a></li>
				<li class="num"><a href="/?pagina=5">5</a></li>
				<li class="num"><a href="/?pagina=6">6</a></li>
				<li class="num"><a href="/?pagina=7">7</a></li>
				<li class="num"><a href="/?pagina=8">8</a></li>
				<li class="num"><a href="/?pagina=9">9</a></li>
				<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
				<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
			</ul>
		</div>-->

	</div>

	<div class="items">

		<ul class="thumbnails">
		
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
		
		</ul>

	</div>

</div>


<div class="cards-list-alt" id="batches-list">

	<div class="top">
	
		<div><h3>Leilões Extra Judiciais</h3></div>
		
		<hr class="divisão_hr">

		<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

		<div class="pagination">
			<ul id="yw1" class="yiiPager">
				<li class="first disabled"><a href="/">&lt;&lt;</a></li>
				<li class="previous disabled"><a href="/">&lt;</a></li>
				<li class="num active"><a href="/">1</a></li>
				<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
				<li class="num"><a href="/?pagina=3">3</a></li>
				<li class="num"><a href="/?pagina=4">4</a></li>
				<li class="num"><a href="/?pagina=5">5</a></li>
				<li class="num"><a href="/?pagina=6">6</a></li>
				<li class="num"><a href="/?pagina=7">7</a></li>
				<li class="num"><a href="/?pagina=8">8</a></li>
				<li class="num"><a href="/?pagina=9">9</a></li>
				<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
				<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
			</ul>
		</div>-->

	</div>

	<div class="items">

		<ul class="thumbnails">
		
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
		
		</ul>

	</div>

</div>

<div class="cards-list-alt" id="batches-list">

	<div class="top">
	
		<div><h3>Leilões de Financeiras</h3></div>
		
		<hr class="divisão_hr">

		<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

		<div class="pagination">
			<ul id="yw1" class="yiiPager">
				<li class="first disabled"><a href="/">&lt;&lt;</a></li>
				<li class="previous disabled"><a href="/">&lt;</a></li>
				<li class="num active"><a href="/">1</a></li>
				<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
				<li class="num"><a href="/?pagina=3">3</a></li>
				<li class="num"><a href="/?pagina=4">4</a></li>
				<li class="num"><a href="/?pagina=5">5</a></li>
				<li class="num"><a href="/?pagina=6">6</a></li>
				<li class="num"><a href="/?pagina=7">7</a></li>
				<li class="num"><a href="/?pagina=8">8</a></li>
				<li class="num"><a href="/?pagina=9">9</a></li>
				<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
				<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
			</ul>
		</div>-->

	</div>

	<div class="items">

		<ul class="thumbnails">
		
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
		
		</ul>

	</div>

</div>

<div class="cards-list-alt" id="batches-list">

	<div class="top">
	
		<div><h3>Pesquisa Rapida</h3></div>
		
		<hr class="divisão_hr">

		<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

		<div class="pagination">
			<ul id="yw1" class="yiiPager">
				<li class="first disabled"><a href="/">&lt;&lt;</a></li>
				<li class="previous disabled"><a href="/">&lt;</a></li>
				<li class="num active"><a href="/">1</a></li>
				<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
				<li class="num"><a href="/?pagina=3">3</a></li>
				<li class="num"><a href="/?pagina=4">4</a></li>
				<li class="num"><a href="/?pagina=5">5</a></li>
				<li class="num"><a href="/?pagina=6">6</a></li>
				<li class="num"><a href="/?pagina=7">7</a></li>
				<li class="num"><a href="/?pagina=8">8</a></li>
				<li class="num"><a href="/?pagina=9">9</a></li>
				<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
				<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
			</ul>
		</div>-->

	</div>
	
	<div class="row " style="margin-top:20px">
        
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
    
    </div>
	
	<div class="row " style="margin-top:20px">
        
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
    
    </div>
	
	<div class="row " style="margin-top:20px">
        
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
		
		<div class="span3 text-center">
			<div class="fundo_classes" style="">
				<font class="font_protudo" face="arial"><b><span style="cursor: pointer;">Leiloes Judiciais</span></b></font>
			</div>
		</div>
    
    </div>

</div>
















