<?=$this->headScript()->prependFile('js/application/home.js');?>


<?php echo $this->partial('application/partials/banner_princ'); ?>

	
<div id="content" class="container">

	<div class="cards-list-alt" id="batches-list">

		<div class="top">
		
			<div><h3 class="linha_destaque">Leilões Judiciais</h3></div>
			
			<hr class="divisão_hr">

			<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

			<div class="pagination">
				<ul id="yw1" class="yiiPager">
					<li class="first disabled"><a href="/">&lt;&lt;</a></li>
					<li class="previous disabled"><a href="/">&lt;</a></li>
					<li class="num active"><a href="/">1</a></li>
					<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
					<li class="num"><a href="/?pagina=3">3</a></li>
					<li class="num"><a href="/?pagina=4">4</a></li>
					<li class="num"><a href="/?pagina=5">5</a></li>
					<li class="num"><a href="/?pagina=6">6</a></li>
					<li class="num"><a href="/?pagina=7">7</a></li>
					<li class="num"><a href="/?pagina=8">8</a></li>
					<li class="num"><a href="/?pagina=9">9</a></li>
					<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
					<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
				</ul>
			</div>-->

		</div>

		<?php echo $this->partial('application/partials/card_leilao'); ?>

	</div>


	<div class="cards-list-alt" id="batches-list">

		<div class="top">
		
			<div><h3 class="linha_destaque" >Leilões Extra Judiciais</h3></div>
			
			<hr class="divisão_hr">

			<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

			<div class="pagination">
				<ul id="yw1" class="yiiPager">
					<li class="first disabled"><a href="/">&lt;&lt;</a></li>
					<li class="previous disabled"><a href="/">&lt;</a></li>
					<li class="num active"><a href="/">1</a></li>
					<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
					<li class="num"><a href="/?pagina=3">3</a></li>
					<li class="num"><a href="/?pagina=4">4</a></li>
					<li class="num"><a href="/?pagina=5">5</a></li>
					<li class="num"><a href="/?pagina=6">6</a></li>
					<li class="num"><a href="/?pagina=7">7</a></li>
					<li class="num"><a href="/?pagina=8">8</a></li>
					<li class="num"><a href="/?pagina=9">9</a></li>
					<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
					<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
				</ul>
			</div>-->

		</div>

		<?php echo $this->partial('application/partials/card_leilao'); ?>

	</div>

	<div class="cards-list-alt" id="batches-list">

		<div class="top">
		
			<div><h3 class="linha_destaque">Leilões de Financeiras</h3></div>
			
			<hr class="divisão_hr">

			<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

			<div class="pagination">
				<ul id="yw1" class="yiiPager">
					<li class="first disabled"><a href="/">&lt;&lt;</a></li>
					<li class="previous disabled"><a href="/">&lt;</a></li>
					<li class="num active"><a href="/">1</a></li>
					<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
					<li class="num"><a href="/?pagina=3">3</a></li>
					<li class="num"><a href="/?pagina=4">4</a></li>
					<li class="num"><a href="/?pagina=5">5</a></li>
					<li class="num"><a href="/?pagina=6">6</a></li>
					<li class="num"><a href="/?pagina=7">7</a></li>
					<li class="num"><a href="/?pagina=8">8</a></li>
					<li class="num"><a href="/?pagina=9">9</a></li>
					<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
					<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
				</ul>
			</div>-->

		</div>

		<?php echo $this->partial('application/partials/card_leilao'); ?>

	</div>

	<?php echo $this->partial('application/partials/pesquisa_rapida'); ?>
	
</div>

<div id="main-nav-tabs-baixo" class="hidden-phone" style="display: none">

	<div class="container">
		<div class="navbar">
			<ul class="nav">
			  <li class="menu_baixo_unidade"><a STYLE="COLOR:#FE821F"><b>UNIDADES:</b></a></li>
			  <li><a>LEILÕES DO LEILOEIRO - GOIÂNIA</a></li>
			  <li><a>LEILÕES DO LEILOEIRO - BRASILIA</a></li>
			  <li><a>LEILÕES DO LEILOEIRO - UBERLANDIA</a></li>
			</ul>
			
			
		</div>
	</div>
</div>
















