<div id="content" class="container">

	<div><h3 class="linha_destaque">Como Funciona</h3></div>
			
	<hr class="divisão_hr">
	
	<div class="row" style="margin-top:0px;">

		<div class="span3 text-center " style="">
			<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 3;" face="arial">
				<i class="fa fa-info-circle" style="font-size: 6.8em; margin-top:10px"></i></br>
				<b><span style="cursor: pointer;" onclick="altera_pgr('trabalhe_conosco')">TRABALHE CONOSCO</span></b></font>
			</div>
		</div>

		<div class="span3 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 3;" face="arial">
			<i class="fa fa-id-card-o" style="font-size: 6.8em; margin-top:10px"></i></br>
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_aprendiz')">PROGRAMA APRENDIZ</span></b></font></div>
		</div>

		<div class="span3 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 3;" face="arial">
			<i class="fa fa-gavel" style="font-size: 6.8em; margin-top:10px"></i></br>
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_estagio')">PROGRAMA ESTAGIO</span></b></font></div>
		</div>

		<div class="span3 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 3;" face="arial">
			<i class="fa fa-handshake-o" style="font-size: 6.8em; margin-top:10px"></i></br>
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_treinee')">PROGRAMA TREINEE</span></b></font></div>
		</div>

	</div>
	
	<div class="row" style="margin-top:40px">

		<div class="span12 box_color ">
		
				<div class="margem">
					<h4><b>Passo 1</b></h4>
					
					<p>
					
						Esta é a seção do plano na qual você apresenta um breve resumo da organização da sua empresa ou negócio, sua história, 
						seu status atual e suas projeções futuras para pesquisa e desenvolvimento, se for o caso. Enfatize as características 
						únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. Dê uma idéia do que você espera conseguir em 
						três ou cinco anos. A descrição legal da empresa deve conter o seguinte Esta é a seção do plano na qual você apresenta um 
						breve resumo da organização da sua empresa ou negócio, sua história, seu status atual e suas projeções futuras para pesquisa e 
						desenvolvimento, se for o caso. Enfatize as características únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. 
						Dê uma idéia do que você espera conseguir em três ou cinco anos. A descrição legal da empresa deve conter o seguinte
					
					</p>
				
				</div>
		
		</div>

	</div>
	
	<div class="row" style="margin-top:40px">

		<div class="span12 box_color ">
		
				<div class="margem">
					<h4><b>Passo 1</b></h4>
					
					<p>
					
						Esta é a seção do plano na qual você apresenta um breve resumo da organização da sua empresa ou negócio, sua história, 
						seu status atual e suas projeções futuras para pesquisa e desenvolvimento, se for o caso. Enfatize as características 
						únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. Dê uma idéia do que você espera conseguir em 
						três ou cinco anos. A descrição legal da empresa deve conter o seguinte Esta é a seção do plano na qual você apresenta um 
						breve resumo da organização da sua empresa ou negócio, sua história, seu status atual e suas projeções futuras para pesquisa e 
						desenvolvimento, se for o caso. Enfatize as características únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. 
						Dê uma idéia do que você espera conseguir em três ou cinco anos. A descrição legal da empresa deve conter o seguinte
					
					</p>
				
				</div>
		
		</div>

	</div>
	
	<div class="row" style="margin-top:40px">

		<div class="span12 box_color ">
		
				<div class="margem">
					<h4><b>Passo 1</b></h4>
					
					<p>
					
						Esta é a seção do plano na qual você apresenta um breve resumo da organização da sua empresa ou negócio, sua história, 
						seu status atual e suas projeções futuras para pesquisa e desenvolvimento, se for o caso. Enfatize as características 
						únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. Dê uma idéia do que você espera conseguir em 
						três ou cinco anos. A descrição legal da empresa deve conter o seguinte Esta é a seção do plano na qual você apresenta um 
						breve resumo da organização da sua empresa ou negócio, sua história, seu status atual e suas projeções futuras para pesquisa e 
						desenvolvimento, se for o caso. Enfatize as características únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. 
						Dê uma idéia do que você espera conseguir em três ou cinco anos. A descrição legal da empresa deve conter o seguinte
					
					</p>
				
				</div>
		
		</div>

	</div>
	
	<div class="row" style="margin-top:40px">

		<div class="span12 box_color ">
		
				<div class="margem">
					<h4><b>Passo 1</b></h4>
					
					<p>
					
						Esta é a seção do plano na qual você apresenta um breve resumo da organização da sua empresa ou negócio, sua história, 
						seu status atual e suas projeções futuras para pesquisa e desenvolvimento, se for o caso. Enfatize as características 
						únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. Dê uma idéia do que você espera conseguir em 
						três ou cinco anos. A descrição legal da empresa deve conter o seguinte Esta é a seção do plano na qual você apresenta um 
						breve resumo da organização da sua empresa ou negócio, sua história, seu status atual e suas projeções futuras para pesquisa e 
						desenvolvimento, se for o caso. Enfatize as características únicas de seu produto ou serviço e , diga como você pode beneficiar o cliente. 
						Dê uma idéia do que você espera conseguir em três ou cinco anos. A descrição legal da empresa deve conter o seguinte
					
					</p>
				
				</div>
		
		</div>

	</div>

</div>