<?=$this->headLink()->setStylesheet('css/application/blog.css');?>

<div id="content" class="container">

<div class="row">

	<div class="span9 hidden-phone">

		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 " style="margin-right:20px">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 " style="margin-right:20px">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 " style="margin-right:20px">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 " style="margin-right:20px">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 " style="margin-right:20px">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 " style="margin-right:20px">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		

	</div>
	
	<div class="span12 visible-phone">

		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 margem" style="">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right" style="margin-bottom:10px">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>		
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 margem" style="">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right" style="margin-bottom:10px">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>	
		
		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
					</div>
					<div class="span6">
						<div class="card-block px-3 margem" style="">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right" style="margin-bottom:10px">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>	

	</div>
	
	<div class="span3">
	
		<div class="label label-success marcador hidden-phone" >
			<span>Especialista</span>
		</div>
		
		<div class="label label-success marcador visible-phone" style="margin-top:20px" >
			<span>Especialista</span>
		</div>
	
		<!--<h4>Especialista</h4>
		<hr class="divisão_hr">-->
		

		<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
		
		<div class="right-text px-3">
			<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		<div class="label label-success marcador-topo">
			<span>Buscar</span>
		</div>
			
			<div class="form-vertical">
                <div class="icon-addon addon-lg ">
                    <input type="text" placeholder="Buscar" class="form-control " id="email">
                    <label for="email" class="fa fa-search" rel="tooltip" title="email"></label>
                </div>
            </div>
		
		<div class="label label-success marcador-topo">
			<span>Temas</span>
		</div>
		
		teste, teste, teste ,teste, teste
		
		<div class="label label-success marcador-topo">
			<span>Receba nossas novidades</span>
		</div>
		
		<div class="right-text px-3">
			<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		
		<form class="form-vertical" id="contact-form" action="/contato" method="post">
			<label for="Contact_name" class="required">Nome</label>
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>

			<label for="Contact_email" class="required">Email</label>
			<input class="span3" name="Contact[email]" id="Contact_email" type="text">
			<span class="help-block error" id="Contact_email_em_" style="display: none"></span>
			
			<span class="help-block error" id="Contact_body_em_" style="display: none"></span>
			
			<div class="form-actions">
				<input class="btn btn-primary" type="submit" name="yt1" value="Enviar">            
				<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
			</div>
		</form>
		
		
	</div>

</div>

</div>










