<?=$this->headLink()->setStylesheet('css/application/blog.css');?>

<div class="row">

	<div class="span9">

		<section class="box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="secao-topo box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="secao-topo box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="secao-topo box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="secao-topo box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="secao-topo box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>
		
		<section class="secao-topo box_color">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span2">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:140px"  class="w-100">
					</div>
					<div class="span7">
						<div class="card-block px-3">
							<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
							<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<a href="/blog/pagina" class="btn btn-primary pull-right">Read More</a>
						</div>
					</div>
				</div>
			<!--</div>-->
		</section>

	</div>
	
	<div class="span3">
	
		<h4>Especialista</h4>
		<hr class="divisão_hr">
		

		<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
		
		<div class="right-text px-3">
			<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		
		<h4>Buscar</h4>
		<hr class="divisão_hr">
			
			<div class="form-vertical">
                <div class="icon-addon addon-lg ">
                    <input type="text" placeholder="Buscar" class="form-control " id="email">
                    <label for="email" class="fa fa-search" rel="tooltip" title="email"></label>
                </div>
            </div>
		
		<h4>Temas</h4>
		<hr class="divisão_hr">
		
		<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
		
		<h4>Receba nossas novidades</h4>
		<hr class="divisão_hr">
		
		<div class="right-text px-3">
			<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		
		<form class="form-vertical" id="contact-form" action="/contato" method="post">
			<label for="Contact_name" class="required">Nome</label>
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>

			<label for="Contact_email" class="required">Email</label>
			<input class="span3" name="Contact[email]" id="Contact_email" type="text">
			<span class="help-block error" id="Contact_email_em_" style="display: none"></span>
			
			<span class="help-block error" id="Contact_body_em_" style="display: none"></span>
			
			<div class="form-actions">
				<input class="btn btn-primary" type="submit" name="yt1" value="Enviar">            
				<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
			</div>
		</form>
		
		
	</div>

</div>










