<?=$this->headLink()->setStylesheet('css/application/blog.css');?>

<div id="content" class="container">

<div class="row">

	<div class="span9 hidden-phone">

		<?php echo $this->partial('application/partials/card_blog'); ?>		
		
		<?php echo $this->partial('application/partials/card_blog'); ?>
		
		<?php echo $this->partial('application/partials/card_blog'); ?>
		
		<?php echo $this->partial('application/partials/card_blog'); ?>

	</div>
	
	<div class="span12 visible-phone">

		<?php echo $this->partial('application/partials/card_blog'); ?>		
		
		<?php echo $this->partial('application/partials/card_blog'); ?>
		
		<?php echo $this->partial('application/partials/card_blog'); ?>
		
		<?php echo $this->partial('application/partials/card_blog'); ?>

	</div>
	
	<div class="span3">
	
		<div class="label label-padrao marcador hidden-phone" >
			<span>Especialista</span>
		</div>
		
		<div class="label label-padrao marcador visible-phone" style="margin-top:20px" >
			<span>Especialista</span>
		</div>
	
		<!--<h4>Especialista</h4>
		<hr class="divisão_hr">-->
		

		<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
		
		<div class="box_color margem">
			<p style="margin-top:0px;">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		<div class="label label-padrao marcador-topo">
			<span>Pesquisa</span>
		</div>
			
			<div class="form-vertical box_color margem">
                <div class="icon-addon addon-lg ">
                    <input style="width:89%" type="text" placeholder="Pesquisa" class="form-control " id="email">
                    <label for="email" class="fa fa-search" rel="tooltip" title="email"></label>
                </div>
            </div>
		
		<div class="label label-padrao marcador-topo">
			<span>Temas</span>
		</div>
		
		<div class="box_color margem">
			<p style="margin-top:0px;">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		<div class="label label-padrao marcador-topo">
			<span>Receba nossas novidades</span>
		</div>
		
		<div class="box_color margem">
			<p style="margin-top:0px;">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		
		<form class="form-vertical box_color margem" style="margin-top:0px;" id="contact-form" action="/contato" method="post">
			<label for="Contact_name" class="required">Nome</label>
			<input style="width:95%" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>

			<label for="Contact_email" class="required">Email</label>
			<input style="width:95%" name="Contact[email]" id="Contact_email" type="text">
			<span class="help-block error" id="Contact_email_em_" style="display: none"></span>
			
			<span class="help-block error" id="Contact_body_em_" style="display: none"></span>
			
			<div class="form-actions" style="margin-bottom:10px">
				<input class="btn btn-primary" type="submit" name="yt1" value="Enviar">            
				<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
			</div>
		</form>
		
		
	</div>

</div>

</div>










