
<div id="page-batch-detail">

<div class="row" style="margin-bottom: 20px;">
	<div class="span8">
		
		<h3 class="page-header" style="">Titulo do Blog</h3>
		<div id="main-carousel" class="carousel slide">
			<ol class="carousel-indicators">
				<li data-target="#main-carousel" data-slide-to="0" class=""></li>
				<li data-target="#main-carousel" data-slide-to="1" class="active"></li>
			</ol>
			<div class="carousel-inner">
				<div class="item">
					<img src="https://cdn.megaleiloes.com.br/public/batches/16190/06dc17aa8f03e10b2ab8b356a18ddb89_670x380.jpg" 
					alt="Apartamento 51 m² - Jardim Umarizal - São Paulo - SP" style="width:100%">
				</div>
				<div class="item active">
					<img src="https://cdn.megaleiloes.com.br/public/batches/16190/9ba3b3647812c79fe956c54c924a6296_670x380.jpg" 
					alt="Apartamento 51 m² - Jardim Umarizal - São Paulo - SP" style="width:100%">
				</div>
			</div>
			<a class="carousel-control left" href="#main-carousel" data-slide="prev">‹</a>
			<a class="carousel-control right" href="#main-carousel" data-slide="next">›</a>
		</div>
		
		
		<div id="batch-description" class="box_color" style="line-height: 25px; margin-top:30px">
			<p class="margem">Matrícula nº 194.409 do 11º Cartório de Registro de Imóveis de São Paulo/SP - IMÓVEL: Apartamento nº 41 localizado no 4º andar do bloco BL-17, 
			integrante do empreendimento denominado Condomínio  Residencial Parque das Orquídeas, situado à Rua Jaracatiá nº 431 antigo s/nº, 
			Estrada de Campo Limpo nº 6.056 e Estrada dos Mirandas s/nº, no 29º Subdistrito-Santo Amaro, tendo o bloco acesso à Rua Jaracatiá através da Rua 3 
			(de circulação interna), possuindo a área útil de 51,715375 m2, a área comum de 29,180971 m2 já incluída a correspondente a uma vaga indeterminada no 
			estacionamento descoberto, e a área total de 80,896346 m2, correspondendo-lhe a fração ideal de 0,03434066% no terreno do condomínio. Consta no R.5 desta 
			matrícula que o imóvel objeto desta matrícula foi hipotecado à CAIXA ECONÔMICA FEDERAL - CEF. Consta no R.6 desta matrícula que nos autos da Ação de Prestação de 
			Contas, Processo nº 544/92, em trâmite na 32ª Vara Cível do Foro Central da Comarca de São Paulo/SP, requerida por MARCO ANTONIO BASSO e outro contra                 
			</p>
		</div>
		
		<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
		<div class="wrapper">
			<ul class="social-icons icon-circle list-unstyled list-inline" style="margin-left:0px">
				<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
				<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
				<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
				<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
				<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
				<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
			</ul>
		</div>
		
		<h5 style="margin-top:20px"><b>Leia Também:</b></h5>
		
		<h4 style="margin-top:200px"><b>Deixar um comentario</b></h4>
		<hr class="divisão_hr">
		
		<form class="form-vertical" id="contact-form" action="/contato" method="post">
			<label for="Contact_name" class="required">Nome</label>
			<input class="span8" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>

			<label for="Contact_email" class="required">Email</label>
			<input class="span8" name="Contact[email]" id="Contact_email" type="text">
			<span class="help-block error" id="Contact_email_em_" style="display: none"></span>
			
			<label for="Contact_body" class="required">Mensagem </label>
			<textarea rows="7" cols="8" class="span8" name="Contact[body]" id="Contact_body"></textarea>
			<span class="help-block error" id="Contact_body_em_" style="display: none"></span>
			
			<div class="form-actions">
				<input class="btn btn-primary" type="submit" name="yt1" value="Enviar mensagem">            
				<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
			</div>
		</form>

	</div>
	
	<div class="span4">
		
		<div class="label label-success marcador hidden-phone" >
			<span>Especialista</span>
		</div>
		
		<div class="label label-success marcador visible-phone" style="margin-top:20px" >
			<span>Especialista</span>
		</div>
	
		<!--<h4>Especialista</h4>
		<hr class="divisão_hr">-->
		

		<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
		
		<div class="right-text px-3">
			<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		<div class="label label-success marcador-topo">
			<span>Buscar</span>
		</div>
			
			<div class="form-vertical">
                <div class="icon-addon addon-lg ">
                    <input type="text" placeholder="Buscar" class="form-control " id="email">
                    <label for="email" class="fa fa-search" rel="tooltip" title="email"></label>
                </div>
            </div>
		
		<div class="label label-success marcador-topo">
			<span>Temas</span>
		</div>
		
		teste, teste, teste ,teste, teste
		
		<div class="label label-success marcador-topo">
			<span>Receba nossas novidades</span>
		</div>
		
		<div class="right-text px-3">
			<p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
		</div>
		
		
		<form class="form-vertical" id="contact-form" action="/contato" method="post">
			<label for="Contact_name" class="required">Nome</label>
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>

			<label for="Contact_email" class="required">Email</label>
			<input class="span3" name="Contact[email]" id="Contact_email" type="text">
			<span class="help-block error" id="Contact_email_em_" style="display: none"></span>
			
			<span class="help-block error" id="Contact_body_em_" style="display: none"></span>
			
			<div class="form-actions">
				<input class="btn btn-primary" type="submit" name="yt1" value="Enviar">            
				<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
			</div>
		</form>
		
	</div>
</div>



</div>