

<?= $this->doctype() ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Leilão MD - Leilão Online')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge, chrome=1')
			->appendHttpEquiv('cache-control', 'public')
			->appendName('description', 'Somos especializados em leilões eletrônicos 
			judiciais e extrajudiciais. Leilões de bens imóveis e móveis em todo Brasil abaixo do valor de mercado!')
			->appendName('author', 'Leilão MD')
			->appendName('copyright', 'Copyright © Leilão MD 2017 - 2020')
			->appendName('audience', 'all')
			->appendName('language', 'pt_br')
			->appendName('content-language', 'pt_br')
			->appendName('robots', 'index, follow')
			->appendName('application-name', 'Leilão MD')
			->appendName('theme-color', '#009cd7')
			->appendName('apple-mobile-web-app-title', 'Leilão MD')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            /*->prependStylesheet($this->basePath('css/style.css'))*/
			->prependStylesheet($this->basePath('css/application/responsive.css'))
			->prependStylesheet($this->basePath('css/application/main.css'))			
			->prependStylesheet($this->basePath('fonts/fontAwesome/css/font-awesome.min.css'))
			/*->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))*/
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
			->prependFile($this->basePath('js/jquery.yiilistview.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body cz-shortcut-listen="true">
	
	
	
	<div id="page">
	
		<div id="main-nav-tabs" class="hidden-phone menu_topo" style="margin-top:0px; margin-bottom:16px">
			<div class="container">
				<div class="navbar">					
					<ul class="nav pull-right">
					  <li><a href="/portal">PORTAL DO CLIENTE</a></li>
					  <li><a href="/ouvidoria">OUVIDORIA</a></li>
					  <li><a href="/colaborador">PORTAL DO COLABORADOR</a></li>
					  <li><a href="/fale">TRABALHE CONOSCO</a></li>
					</ul>
				</div>
			</div>
		</div>
		
		<div id="menu-phone" class="visible-phone">
		
			<div class="container">
				<ul class="nav nav-tabs nav-stacked text-center">
					<li class=""><a href="/portal">Portal do Cliente</a></li>
				</ul>		
			</div>
		
		</div>
	
		<div id="main-nav">
		
			<div class="container">
			
				<div class="row">
					<div class="brand span4">
					<a style="display: block; " href="/"><img style="width: 285px;!important" 
					src="/img/LOGO.png" alt="Mega Leilões"></a>
					</div>
					<div class="widgets span8 pull-right visible-desktop">
						<style>
						#main-nav .widgets .signup {
						width: 130px;
						padding: 16px 20px;
						color: #FFF;
						font-weight: 700;
						font-size: 14px;
						text-align: center;
						border-top-right-radius: 2px;
						border-bottom-right-radius: 2px;
						border: 0;
						background-color: #008BBF;
						display: inline-block;
						}
						#main-nav .widgets .signup:hover {
						background: #00adef;
						color: #fff;
						}
						#main-nav .widgets .signup .small {
						font-size: 11px;
						font-weight: 400;
						}
						#main-nav .widgets .broker-partner-banner {
						display: inline-block;
						}
						#main-nav .widgets .broker-partner-banner img {
						height: 94px;
						}
						
						</style>
						<!--<div class="pull-left clearfix" style="">
							<a class="auditorium-btn" style="margin-top: 20px; height:63px" >Acessar </br> Auditório</a>
							<a class="auditorium-btn" style="margin-top: 3px;" >Leilão no Ar</a>
						</div>-->
						
						<div class="pull-right" style="margin-top: 10px;">
							<a class="btn signup light-btn" href="/cadastro" style="margin: 10px 0px 0px 10px; height:63px; background-color:#FB720C">
							<p style="font-size:18px">Acessar</p> <span class="large" style="font-size:18px">Auditório</span>
							<a class="btn signup light-btn" href="/cadastro" style="margin: 10px 0px 0px 10px; height:63px; background-color:#FB720C"><p>WHATSAPP</p>
							<span class="large" style="font-size:16px">(62) 98101-0983</span></a>
							<!--<form style="float: left; margin: 10px 20px 20px 20px;" class="form-inline" id="yw1" action="/login" method="post">
								<div class="title" style="color: #999;">Acesse sua conta</div>
								<input style="width: 180px; margin-bottom: 2px; border-color: #F1F1F1;" placeholder="Nome de usuário ou email" 
								name="Login[username]" id="Login_username" type="text" maxlength="45">
								<br>
								<input style="width: 109px; border-color: #F1F1F1;" placeholder="Senha" name="Login[password]" id="Login_password" 
								type="password" maxlength="45">
								<input value="https://www.megaleiloes.com.br/" name="Login[returnUrl]" id="Login_returnUrl" 
								type="hidden">
								<button style="width: 68px; border: 1px solid #DDD; margin: 0;" class="btn" id="yw2" type="submit" name="yt0">Entrar</button>
								<br>
								<a href="/recuperar-senha">Esqueceu sua senha?</a>
							</form>-->
							<!--<a class="btn signup light-btn" href="/cadastro" style="margin-top:10px">CRIAR CONTA <i class="icon-chevron-right"></i>
							<span class="small">Cadastre-se agora e participe dos leilões.</span></a>-->
							<a class="btn signup light-btn" href="/cadastro" style="margin: 10px 0px 0px 10px; height:63px; background-color:#FB720C"><p>UNIDADE GOIÂNIA</p>
							<span class="large" style="font-size:16px">(62) 4101-0528</span></a>
						</div>

						            
					</div>
				</div>
			
			</div>
		
		</div>
		
		
		<div id="main-nav-tabs" class="hidden-phone" style="margin-top:-5px">
			<div class="container" style="height:50px">
				<div class="navbar" style="margin-top:5px">
					<ul class="nav">

						<li class="rm_border"><a href="#">NOSSOS SITES:</a></li>
						<li>
						<div class="btn-toolbar">
						<div class="btn-group">
						<a class="btn dropdown-toggle" data-toggle="dropdown">	Leiloes MD <span class="caret"></span></a>
						<ul class="dropdown-menu">
						<li><a href="#">Leiloes goias</a></li>
						<li><a href="#">Leiloes Brasilia</a></li>
						<li><a href="#">Leiloes teste</a></li>
						</ul>
						</div>
						</div>

						</li>

						
					  
					</ul>
					
					<ul class="nav pull-right">
					  <li class="active"><a href="/">INICIO</a></li>
					  <li><a href="/empresa">EMPRESA</a></li>
					  <li><a href="/agenda">AGENDA</a></li>
					  <li><a href="/leilao">LEILÕES</a></li>
					  <li><a href="/servicos">SERVIÇOS</a></li>
					  <li><a href="/blog">BLOG</a></li>
					  <li><a href="/contato">CONTATO</a></li>
					  <li><a href="/funciona">COMO FUNCIONA</a></li>
					</ul>
				</div>
			</div>
		</div>
		
		<div id="menu-phone" class="visible-phone">
		
			<div class="container">
				<ul class="nav nav-tabs nav-stacked text-center">
					<li class=""><a href="/">Inicio</a></li>
					<li><a href="/empresa">Empresa</a></li>
					<li><a href="/agenda">Agenda</a></li>
					<li><a href="/leilao">Leilões</a></li>
					<li><a href="/servicos">Serviço</a></li>
					<li><a href="/blog">Blog</a></li>
					<li><a href="/contato">Contato</a></li>
					<li><a href="/funciona">Como Funciona</a></li>
					<li style="color:white"><a>
						<select class="" style="width:100%">
						
							<option>Leilão MD</option>
							<option>Leilão MD</option>
							<option>Leilão MD</option>
							<option>Leilão MD</option>
							<option>Leilão MD</option>
							<option>Leilão MD</option>
						
						</select>
						
					
					</a></li>
				</ul>		
			</div>
		
		</div>
				
			<?= $this->content ?>
		
		</div>		
		
		<div class="footer hidden-phone">
			<div class="container">
				<div class="row">
					<div class="span2">
						<ul>
							<li class="title">EMPRESA</li>
							<li><a href="/empresa">QUEM SOMOS</a></li>
							<li><a href="/empresa">MISSÃO</a></li>
							<li><a href="/empresa">VALORES</a></li>
							<li><a href="/empresa">VISÃO</a></li>
						</ul>
					</div>
					<div class="span2">
					
						<ul>
							<li class="title">LEILÕES</li>
							<li><a href="/">AERONAVES</a></li>
							<li><a href="/">VEICULOS</a></li>
							<li><a href="/">IMOVEIS</a></li>
							<li><a href="/">EMBARCAÇÕES</a></li>
						</ul>

					</div>
					<div class="span2">
						<ul>
							<li class="title">SERVIÇO</li>
							<li><a href="/">VENDA DIRETA</a></li>
							<li><a href="/">LEILÕES JUDICIAIS</a></li>
							<li><a href="/">LEILÕES EXTRAS-JUDICIAIS</a></li>
							<li><a href="/">LEILÕES DE FINANCEIRA</a></li>
						</ul>
					</div>
					<div class="span2">
						<ul>
							<li class="title">CONTATO</li>
							<li><a href="/">ATENDIMENTO ONLINE</a></li>
							<li><a href="/">QUERO COMPRAR</a></li>
							<li><a href="/">QUERO VENDER</a></li>
							<li><a href="/contato">LOCALIZAÇÃO</a></li>
						</ul>
					</div>
					<div class="span2">
						<ul>
							<li class="title">PORTAL DO CLIENTE</li>
							<li><a href="/">CADASTRA-SE</a></li>
							<li><a href="/">FAZER LOGIN</a></li>
							<li class="title" style="margin-top:20px">SUPORTE</li>
							<li><a href="/">REGRAS BASICAS</a></li>
							<li><a href="/">DUVIDAS FREQUENTES</a></li>
							<li><a href="/">SEGURANÇA</a></li>
						</ul>
					</div>
					<div class="span2 wrapper">
						<ul class="midia_social social-icons icon-rounded  list-unstyled list-inline" style="list-style-type: none;">
							<li class="title">Nossos canais</li>
							<li>
								<!--<i class="icon icon-facebook-sign"></i>-->
								<a href="#"><i class="fa fa-facebook"></i>
								<a href="/" target="_blank">FACEBOOK</a>
							</li>
							<li>
								<!--<i class="icon icon-instagram"></i>-->
								<a href="#"><i class="fa fa-instagram"></i></a>
								<a href="/" target="_blank">INSTAGRAM</a>
							</li>
							<li>
								<!--<i class="icon icon-google-plus"></i>-->
								<a href="#"><i class="fa fa-google-plus"></i></a>
								<a href="/" target="_blank">GOOGLE PLUS</a>
							</li>
							<li>
								<!--<i class="icon icon-youtube-play"></i>-->
								<a href="#"><i class="fa fa-youtube-square"></i></a>
								<a href="/" target="_blank">YouTube</a>
							</li>
							<li>
								<!--<i class="icon icon-pinterest"></i>-->
								<a href="#"><i class="fa fa-pinterest"></i></a>
								<a href="/" target="_blank">PINTEREST</a>
							</li>
							<li>
								<!--<i class="icon icon-twitter"></i>-->
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="/" target="_blank">Twitter</a>
							</li>
						</ul>
					</div>
					
					<!--<div class="span2">
						<ul class="midia_social">
							<li class="title">Nossos canais</li>
							<li>
								<i class="icon icon-facebook-sign"></i> 
								<i class="icon icon-instagram"></i> 
								<i class="icon icon-google-plus"></i> 
								<i class="icon icon-youtube-play"></i> 
								<i class="icon icon-pinterest"></i>
								<i class="icon icon-twitter"></i> 
								
							</li>
						</ul>
					</div>-->

					<!--<div class="span2 pull-right">
						<img src="https://cdn.megaleiloes.com.br/assets/img/poder_judiciario.png" width="134" height="68" 
						style="margin-right: 30px;" alt="Site e sistema homologado pelo tribunal de justíça." 
						title="Site e sistema homologado pelo tribunal de justíça." data-toggle="tooltip"><br class="visible-tablet">
					</div>-->
				</div>
				<div class="copy">Copyright © Mega Leilões 2013. Todos os direitos reservados.</div>
			</div>
			
		</div>		
		
		
		<div class="footer text-center visible-phone">
			<div class="container">
				<div class="row">
					<div class="span2">
						<ul>
							<li class="title">EMPRESA</li>
							<li><a href="/empresa">QUEM SOMOS</a></li>
							<li><a href="/empresa">MISSÃO</a></li>
							<li><a href="/empresa">VALORES</a></li>
							<li><a href="/empresa">VISÃO</a></li>
						</ul>
					</div>
					<div class="span2">
					
						<ul>
							<li class="title">LEILÕES</li>
							<li><a href="/">AERONAVES</a></li>
							<li><a href="/">VEICULOS</a></li>
							<li><a href="/">IMOVEIS</a></li>
							<li><a href="/">EMBARCAÇÕES</a></li>
						</ul>

					</div>
					<div class="span2">
						<ul>
							<li class="title">SERVIÇO</li>
							<li><a href="/">VENDA DIRETA</a></li>
							<li><a href="/">LEILÕES JUDICIAIS</a></li>
							<li><a href="/">LEILÕES EXTRAS-JUDICIAIS</a></li>
							<li><a href="/">LEILÕES DE FINANCEIRA</a></li>
						</ul>
					</div>
					<div class="span2">
						<ul>
							<li class="title">CONTATO</li>
							<li><a href="/">ATENDIMENTO ONLINE</a></li>
							<li><a href="/">QUERO COMPRAR</a></li>
							<li><a href="/">QUERO VENDER</a></li>
							<li><a href="/contato">LOCALIZAÇÃO</a></li>
						</ul>
					</div>
					<div class="span2">
						<ul>
							<li class="title">PORTAL DO CLIENTE</li>
							<li><a href="/">CADASTRA-SE</a></li>
							<li><a href="/">FAZER LOGIN</a></li>
							<li class="title" style="margin-top:10px">SUPORTE</li>
							<li><a href="/">REGRAS BASICAS</a></li>
							<li><a href="/">DUVIDAS FREQUENTES</a></li>
							<li><a href="/">SEGURANÇA</a></li>
						</ul>
					</div>
					<div class="span2 wrapper text-left">
						<ul class="midia_social_phone social-icons icon-rounded  list-unstyled list-inline">
							<li class="title" style="margin-left:30%">Nossos canais</li>
							<li>
								<!--<i class="icon icon-facebook-sign"></i>-->
								<a href="#"><i class="fa fa-facebook"></i>
								<a href="/" target="_blank">FACEBOOK</a>
							</li>
							<li>
								<!--<i class="icon icon-instagram"></i>-->
								<a href="#"><i class="fa fa-instagram"></i></a>
								<a href="/" target="_blank">INSTAGRAM</a>
							</li>
							<li>
								<!--<i class="icon icon-google-plus"></i>-->
								<a href="#"><i class="fa fa-google-plus"></i></a>
								<a href="/" target="_blank">GOOGLE PLUS</a>
							</li>
							<li>
								<!--<i class="icon icon-youtube-play"></i>-->
								<a href="#"><i class="fa fa-youtube-square"></i></a>
								<a href="/" target="_blank">YouTube</a>
							</li>
							<li>
								<!--<i class="icon icon-pinterest"></i>-->
								<a href="#"><i class="fa fa-pinterest"></i></a>
								<a href="/" target="_blank">PINTEREST</a>
							</li>
							<li>
								<!--<i class="icon icon-twitter"></i>-->
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="/" target="_blank">Twitter</a>
							</li>
						</ul>
					</div>

					<!--<div class="span2 pull-right">
						<img src="https://cdn.megaleiloes.com.br/assets/img/poder_judiciario.png" width="134" height="68" 
						style="margin-right: 30px;" alt="Site e sistema homologado pelo tribunal de justíça." 
						title="Site e sistema homologado pelo tribunal de justíça." data-toggle="tooltip"><br class="visible-tablet">
					</div>-->
				</div>
				<div class="copy">Copyright © Mega Leilões 2013. Todos os direitos reservados.</div>
			</div>
			
		</div>
	
	</div>
	
    </body>
</html>
