<?=$this->flashMessenger()
->setMessageOpenFormat('<div class="alert text-center alert-danger alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>')
->setMessageSeparatorString('</p><p>')
->setMessageCloseString('</div>')
->render('error', array('alert', 'alert-danger'));?>

<div class="box_overlay">
	
	<div class="overlay" style="display:none">
	  <i class="fa fa-refresh fa-spin"></i>
	</div>
	
<div class="login-box">

	<div class="login-logo">
		<b>Leilão</b>MD
	</div>

	<div class="login-box-body">
	
		<p class="login-box-msg"><b>Entrar</b></p>

		<?= $this->form()->openTag($form); ?>
		
			<?= $this->formElement($form->get('redireciona_url')); ?>
			<?= $this->formElement($form->get('csrf')); ?>
		
			<div class="form-group has-feedback">
				<?= $this->formElement($form->get('cpf_usr')); ?>
				<span class="glyphicon glyphicon-user form-control-feedback"></span>
			</div>
			<div class="form-group has-feedback">
				<?= $this->formElement($form->get('senha_usr')); ?>
				<span class="glyphicon glyphicon-lock form-control-feedback"></span>
			</div>
			<div class="row">
			
				<div class="col-xs-8">
					<div class="checkbox icheck">
						<label>
							<?= $this->formElement($form->get('chk_lembrar')); ?> Lembrar
						</label>
					</div>
				</div>

				<div class="col-xs-4">
					<?= $this->formElement($form->get('btn_login')); ?>
				</div>

			</div>
			
		<?= $this->form()->closeTag(); ?>

		<a href="#">Esqueci minha senha.</a><br>

	</div>

</div>
</div>

<?php

$this->headScript()->appendFile($this->basePath('js/sgs/autentica/login.js'), 'text/javascript');
$this->headScript()->appendFile($this->basePath('js/sgs/funcoes.js'), 'text/javascript');

?>