<div style="margin-bottom: 20px; margin-top: -20px;" class="hidden-phone carousel slide" id="main-carousel">
	<ol class="carousel-indicators">
		<li data-target="#main-carousel" data-slide-to="0" class=""></li>
		<li data-target="#main-carousel" data-slide-to="1" class=""></li>
		<li data-target="#main-carousel" data-slide-to="2" class=""></li>	
		<li data-target="#main-carousel" data-slide-to="3" class=""></li>
		<li data-target="#main-carousel" data-slide-to="4" class=""></li>
		<li data-target="#main-carousel" data-slide-to="5" class=""></li>
		<li data-target="#main-carousel" data-slide-to="6" class=""></li>
		<li data-target="#main-carousel" data-slide-to="7" class="active"></li>
		<li data-target="#main-carousel" data-slide-to="8" class=""></li>
		<li data-target="#main-carousel" data-slide-to="9" class=""></li>
		<li data-target="#main-carousel" data-slide-to="10" class=""></li>
		<li data-target="#main-carousel" data-slide-to="11" class=""></li>
	</ol>
	<div class="carousel-inner">
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/bd062d822072d8d72f6f8dbd620ee130_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - IMÓVEIS SANTANDER - EX-AGÊNCIAS" width="700">
			</a>
		</div>
		<div height="250" class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/bae9f8543ed0585521ca7a1172217495_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - BRICKELL 06 LOTES">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/3786992f9aa78a1fd42e8b9e51c55717_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - IMÓVEL RURAL 11.917 HA">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/b96e6e9c46a0d83f87388c6320a6132f_1170x250.jpg"
				alt="LEILÃO SANTANDER - IMÓVEL COMERCIAL (EX-AGÊNCIA) 1.232 m² - SBC - SP">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/385d89b97b10e41a59bf07dafddd749a_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - TERRENO 16.391 m²">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/65ac5202f191e54027aa9a7a0d4774b5_1170x250.jpg" 
				alt="Leilão de Imóveis Comerciais - BRL Trust Investimentos">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/65fc1c7b08affb542d3c1d82c84bec38_1170x250.jpg" 
				alt="Leilão de Imóveis Comerciais - BRL Trust Investimentos LOTES 08 E 10">
			</a>
		</div>
		<div class="item active">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/2ccca05777aabf479e8d9693e0e44d79_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - CASA 326 m² - SANTANA DE PARNAÍBA - SP">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/64611bc9921f0a9ca6ee6e4a5ab5eba1_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - TERRENO 18.388 m²">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/4b21c62b5bd03893246dfcb9e666a08e_1170x250.jpg" 
				alt="LEILÃO JUDICIAL - ZANINI">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/932fc7c7059336d6a13dc2329fa41abf_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - BANCO ITAÚ 10 LOTES">
			</a>
		</div>
		<div class="item">
			<a href="/">
				<img src="https://cdn.megaleiloes.com.br/public/carrousel/c8fd81def5af98aff6bafe6a68609832_1170x250.jpg" 
				alt="LEILÃO EXTRAJUDICIAL - ÁREA DE TERRAS 58.181 m²">
			</a>
		</div>
	</div>

	<a class="carousel-control left" href="#main-carousel" data-slide="prev">‹</a>
	<a class="carousel-control right" href="#main-carousel" data-slide="next">›</a>

</div>