

<div class="items">

	<ul class="thumbnails">
	
		<li class="item-row card primary span3 ">
			<a class="type" href="/">Judicial</a>    
			<a class="card-image" href="/leilao/pagina">
				<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
				alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
			</a>    
			<div class="card-status-numbers">
				<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
				<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
			</div>
			
			<a class="card-header2" href="/leilao/pagina">
				<span class="instance">1ª praça</span>
				<span class="status">ABERTO PARA LANCES</span>
			</a>
			
			<a class="card-header" href="/leilao/pagina">
				<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
			</a>
			<div class="card-body">
				<ul class="description">
					<li><span class="lih">Lote</span>J16144 / Lote 1</li>
					<li><span class="lih">Localidade</span><a href="/">Garça, SP</a></li>
				</ul>
				<ul class="values">
					<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 204.565,21</b></li>
					<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 122.739,13</b></li>
				</ul>
			</div>
			<div class="clearfix"></div>
		</li>
		
		<li class="item-row card primary span3 ">
			<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
			<a class="card-image" href="/leilao/pagina">
				<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
				alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
			</a>    
			<div class="card-status-numbers">
				<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
				<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
			</div>
			
			<a class="card-header2" href="/leilao/pagina">
				<span class="instance">1ª praça</span>
				<span class="status">ABERTO PARA LANCES</span>
			</a>
			
			<a class="card-header" href="/leilao/pagina">
				<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
			</a>
			<!--<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
			data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
				<i class="icon icon-legal"></i>
			</button>-->
			<div class="card-body">
				<ul class="description margem">
					<li><span class="lih">Lote</span>J16144 / Lote 1</li>
					<li style="display: none!important;"><span class="lih">Categoria</span>
						<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
					</li>
					<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
				</ul>
				<ul class="values">
					<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 204.565,21</b></li>
					<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 122.739,13</b></li>
				</ul>
			</div>
			<div class="clearfix"></div>
		</li>
		
		<li class="item-row card primary span3 ">
			<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
			<a class="card-image" href="/leilao/pagina">
				<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
				alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
			</a>    
			<div class="card-status-numbers">
				<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
				<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
			</div>
			
			<a class="card-header2" href="/leilao/pagina">
				<span class="instance">1ª praça</span>
				<span class="status">ABERTO PARA LANCES</span>
			</a>
			
			<a class="card-header" href="/leilao/pagina">
				<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
			</a>
			<!--<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
			data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
				<i class="icon icon-legal"></i>
			</button>-->
			<div class="card-body">
				<ul class="description margem">
					<li><span class="lih">Lote</span>J16144 / Lote 1</li>
					<li style="display: none!important;"><span class="lih">Categoria</span>
						<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
					</li>
					<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
				</ul>
				<ul class="values">
					<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 204.565,21</b></li>
					<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 122.739,13</b></li>
				</ul>
			</div>
			<div class="clearfix"></div>
		</li>
		
		<li class="item-row card primary span3 ">
			<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
			<a class="card-image" href="/leilao/pagina">
				<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
				alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
			</a>    
			<div class="card-status-numbers">
				<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
				<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
			</div>
			
			<a class="card-header2" href="/leilao/pagina">
				<span class="instance">1ª praça</span>
				<span class="status">ABERTO PARA LANCES</span>
			</a>
			
			<a class="card-header" href="/leilao/pagina">
				<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
			</a>
			<!--<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
			data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
				<i class="icon icon-legal"></i>
			</button>-->
			<div class="card-body">
				<ul class="description">
					<li><span class="lih">Lote</span>J16144 / Lote 1</li>
					<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
				</ul>
				<ul class="values">
					<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 204.565,21</b></li>
					<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
					<li><span class="lih"></span><b>R$ 122.739,13</b></li>
				</ul>
			</div>
			<div class="clearfix"></div>
		</li>
	
	</ul>

</div>
	
	