<section class="box_color visible-phone">
	
	<div class="span12" style="background-color:#F9860C; color: #fff; height:156px">
	
		<div class="sec_box_dest text-center">
			<p>
			Dia:28 </br>
			Mês:Novembro </br>
			Horario: 13:00 </br>
			</p>
		</div>
	
	</div>
	
	<div class="span12">
		<div class="margem">
		
			<h4 class="card-title"><b>Leilões de Veiculos e de bens diversos</b></h4>
			
			<p class="card-text">
				Sucata Automóvel VW Voyage CL MB 2015 2015 Gas/Alc Preta ( Sinistrado ) Renavam:01049373410
			</p>
			
			<p class="card-text">
			<span>Quantidade de bens: 13</span> </br>
			</p>
			<p class="card-text" style="margin-top:4px">
				<span><a>Apresentação</a></span>
				<span class="edital"><a>Edital</a></span>
			</p>
			
		</div>	
		
	</div>
	
	<div class="span12">
		<div class="sec_desc_dir margem" style="padding: 0;">
		
			<span class="ref" style="margin-left: 10px;"><b>Ref 0100</b></span>
			<span class="pull-right" style="margin-right: 10px;">ONLINE PRESENCIAL</span>
			
		</div>
	</div>

</section>