<section class="box_color">
	<!--<div class="card">-->
		<div class="row" >
			<div class="span3 hidden-phone">
				<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg"  class="w-100">
			</div>
			<div class="span6 hidden-phone" style="margin-left:15px">
				<div class=" margem">
					<h4 class="card-title">Lorem ipsum dolor sit amet</h4>
					<p class="card-text" style="margin-top:4px">
					Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
					Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
					</p>
					<h5 style="margin-top:0px"><b>Compartilhe:</b></h5>
					<div class="wrapper" style="margin-top:0px">
						<ul class="social-icons icon-rounded  list-unstyled list-inline" style="margin-left:0px">
							<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
							<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
							<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
							<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
							<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
						</ul>
					</div>
					<a href="/blog/pagina" class="btn btn-padrao pull-right hidden-phone">Read More</a>
				</div>
			</div>
			
			<div class="span12 visible-phone">
	
				<section class="box_color" onclick="location.href='/servicos/pagina'" style="cursor:pointer">
					<!--<div class="card">-->
						<div class="row" >
							<div class="span12">
								<div class="margem">
									<h4 class="">Lorem ipsum dolor sit amet</h4>
									<img style="margin-top:10px" src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" 
									style="height:240px;width:340px"  class="w-100">
									<p class="">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
									Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
									<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
									<div class="wrapper" style="margin-top:4px">
										<ul class="social-icons icon-rounded  list-unstyled list-inline" style="margin-left:0px">
											<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
											<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
											<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
											<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
											<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
											<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
										</ul>
									</div>
									
									<a href="/blog/pagina" class="btn btn-padrao pull-right">Read More</a>
								</div>
							</div>
						</div>
					<!--</div>-->
				</section>

			</div>
		</div>
	<!--</div>-->
</section>