<ul>
	<li>
		<a href="#">
			<span class="dia">22</span>
			<span class="mes">nov</span>
		</a>
	</li>
	
	<li>
		<a href="#">
			<span class="dia">22</span>
			<span class="mes">nov</span>
		</a>
	</li>
	
	<li>
		<a href="#">
			<span class="dia">22</span>
			<span class="mes">nov</span>
		</a>
	</li>
	
	<li>
		<a href="#">
			<span class="dia">22</span>
			<span class="mes">nov</span>
		</a>
	</li>
</ul>