<ul>
					
	<li>
		<input type='checkbox' /><span class="lista_tipo_desc">Góias</span>
		<ul>
		
			<li>
				<input type='checkbox' /><span class="lista_tipo_desc">Goânia</span>
			</li>
			<li>
				<input type='checkbox' /><span class="lista_tipo_desc">Anapolis</span>
			</li>
			<li>
				<input type='checkbox' /><span class="lista_tipo_desc">Aparecida de Goiânia</span>
			</li>
		
		</ul>
	</li>

</ul>