<div class="hidden-phone" id="">

	<div class="top">
	
		<div><h3 class="linha_destaque">Pesquisa Rapida</h3></div>
		
		<hr class="divisão_hr">

	</div>
	
	<div class="row " style="margin-top:20px ">
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
	
	</div>
	
	<div class="row " style="margin-top:20px ">
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
	
	</div>
	
	<div class="row " style="margin-top:20px ">
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
		<div class="span2 text-center box_color2" style="height:45px">
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer; margin-top:20px">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
	
	</div>
</div>

<div class="visible-phone" id="">

	<div class="top">
	
		<div><h3 class="linha_destaque">Pesquisa Rapida</h3></div>
		
		<hr class="divisão_hr">

	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>
	
	<div class="row box_color2" style="margin-top:20px; height:45px">
		
		<div class="span12 text-center box_color2" >
			<div class="fundo_classes" style="">
				<font class="font_protudo" style="margin-top:20px" face="arial" ><b>
				<span style="cursor: pointer;">Leiloes Judiciais</span>
				</b></font>
			</div>
		</div>
		
	
	</div>

</div>