<div id="content" class="container">

	<div class="row">

		<div class="span12 box_color ">
		
			<div class="margem">				
				<p>
				
					Este é um canal permanente e de fácil acesso, onde qualquer cliente pode se manifestar, 
					de modo a estabelecer um relacionamento democrático e transparente entre as empresas do grupo. 
					As manifestações (Elogio, Denúncia, Parcerias, Reclamação, Sugestão e Informações) serão encaminhadas para 
					as empresas e entidades que compõem a estrutura organizacional 
					do Grupo Dutra, recebendo o devido tratamento e usadas posteriormente para o aprimoramento de práticas e processos.
				
				</p>
			
			</div>
		
		</div>

	</div>
	
	<div><h3>Assuntos do E-mail</h3></div>
			
	<hr class="divisão_hr">
	
	<div class="row">
	
		<div class="span4">
		
			<div class="text-center" style="background:#003862; height:50px; ">
				<p style="color:white; padding-top:15px">
					<font face="'Titillium Web', sans-serif" style="font-size:18px;">
						<b>RECLAMAÇAO</b>
					</font>
				</p>
			</div>
			
			<div class="text-center box_color margem" style=" height:320px;">
				<p align="justify" class="cor_letra" style="margin-top:10px">
				<font face="'Titillium Web', sans-serif" style="font-size:14px;">
				<b>Descrição: </b>				
				   Demonstração de apreço, reconhecimento ou satisfação sobre nossos serviços prestados ou relativos aos colaboradores que participam do grupo.
				</font>
				</p>
			</div>
		
		
		</div>
		
		<div class="span4">
		
			<div class="text-center" style="background:#003862; height:50px; ">
				<p style="color:white; padding-top:15px">
					<font face="'Titillium Web', sans-serif" style="font-size:18px;">
						<b>DENÚNCIA</b>
					</font>
				</p>
			</div>
			
			<div class="text-center box_color margem" style=" height:320px;">
				<p align="justify" class="cor_letra" style="margin-top:10px">
				<font face="'Titillium Web', sans-serif" style="font-size:14px;">
				<b>Descrição: </b>				
				   Comunicação de irregularidades ocorridas no âmbito da prestação de serviço ou apontamento de exercício negligente ou abusivo dos 
				   colaboradores e funções, como também corrupção, ou improbidade, que venham ferir o código de ética do nosso grupo ou a legislação vigente no Brasil.
				</font>
				</p>
			</div>
		
		
		</div>
		
		<div class="span4">
		
			<div class="text-center" style="background:#003862; height:50px; ">
				<p style="color:white; padding-top:15px">
					<font face="'Titillium Web', sans-serif" style="font-size:18px;">
						<b>PARCERIAS</b>
					</font>
				</p>
			</div>
			
			<div class="text-center box_color margem" style=" height:320px;">
				<p align="justify" class="cor_letra" style="margin-top:10px">
				<font face="'Titillium Web', sans-serif" style="font-size:14px;">
				<b>Descrição: </b>				
				   Canal direto de avaliação e desempenho de parcerias firmadas com empresas, instituições públicas, sindicatos, associações, federações entre outras entidades.
				</font>
				</p>
			</div>
		
		
		</div>
	
	</div>
	
	<div class="row" style="margin-top:20px">
	
		<div class="span4">
		
			<div class="text-center" style="background:#003862; height:50px; ">
				<p style="color:white; padding-top:15px">
					<font face="'Titillium Web', sans-serif" style="font-size:18px;">
						<b>RECLAMAÇAO</b>
					</font>
				</p>
			</div>
			
			<div class="text-center box_color margem" style=" height:320px;">
				<p align="justify" class="cor_letra" style="margin-top:10px">
				<font face="'Titillium Web', sans-serif" style="font-size:14px;">
				<b>Descrição: </b>				
				   Demonstração de apreço, reconhecimento ou satisfação sobre nossos serviços prestados ou relativos aos colaboradores que participam do grupo.
				</font>
				</p>
			</div>
		
		
		</div>
		
		<div class="span4">
		
			<div class="text-center" style="background:#003862; height:50px; ">
				<p style="color:white; padding-top:15px">
					<font face="'Titillium Web', sans-serif" style="font-size:18px;">
						<b>DENÚNCIA</b>
					</font>
				</p>
			</div>
			
			<div class="text-center box_color margem" style=" height:320px;">
				<p align="justify" class="cor_letra" style="margin-top:10px">
				<font face="'Titillium Web', sans-serif" style="font-size:14px;">
				<b>Descrição: </b>				
				   Comunicação de irregularidades ocorridas no âmbito da prestação de serviço ou apontamento de exercício negligente ou abusivo dos 
				   colaboradores e funções, como também corrupção, ou improbidade, que venham ferir o código de ética do nosso grupo ou a legislação vigente no Brasil.
				</font>
				</p>
			</div>
		
		
		</div>
		
		<div class="span4">
		
			<div class="text-center" style="background:#003862; height:50px; ">
				<p style="color:white; padding-top:15px">
					<font face="'Titillium Web', sans-serif" style="font-size:18px;">
						<b>PARCERIAS</b>
					</font>
				</p>
			</div>
			
			<div class="text-center box_color margem" style=" height:320px;">
				<p align="justify" class="cor_letra" style="margin-top:10px">
				<font face="'Titillium Web', sans-serif" style="font-size:14px;">
				<b>Descrição: </b>				
				   Canal direto de avaliação e desempenho de parcerias firmadas com empresas, instituições públicas, sindicatos, associações, federações entre outras entidades.
				</font>
				</p>
			</div>
		
		
		</div>
	
	</div>
	
	<div class="row" style="margin-top:20px">
                        
        <div class="span12 text-center">
            
            <p style="color:#003862; margin-bottom:3px"><font face="arial" style="font-size:19px">Envie um email para</font></p>
            <p style="color:#003862; margin-bottom:3px"><font face="arial" style="font-size:24px">OUVIDORIA@MDIIMOVEIS.COM.BR</font></p>
            <p style="color:#003862; margin-bottom:3px"><font face="arial" style="font-size:19px">com o assunto escolhido acima no título.</font></p>
            
            
        </div>
    
    </div>

</div>