<?=$this->headLink()->setStylesheet('css/application/servico.css');?>

<div id="content" class="container">

<div class="row">

	<div class="span6">
	
		<section class="box_color" onclick="location.href='/servicos/pagina'" style="cursor:pointer">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<div class="margem">
							<h4 class="">Lorem ipsum dolor sit amet</h4>
							<p class="">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
							<div class="wrapper">
								<ul class="social-icons icon-circle list-unstyled list-inline" style="margin-left:0px">
									<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
									<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
									<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
									<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
									<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
									<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="span3"">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:260px;width:340px"  class="w-100">
					</div>
				</div>
			<!--</div>-->
		</section>
	
	</div>
	
	<div class="span6">
	
		<section class="box_color" onclick="location.href='/servicos/pagina'" style="cursor:pointer">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<div class="margem">
							<h4 class="">Lorem ipsum dolor sit amet</h4>
							<p class="">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
							<div class="wrapper">
								<ul class="social-icons icon-circle list-unstyled list-inline" style="margin-left:0px">
									<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
									<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
									<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
									<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
									<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
									<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="span3"">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:260px;width:340px"  class="w-100">
					</div>
				</div>
			<!--</div>-->
		</section>
	
	</div>
	
	
	
</div>

<div class="row">

	<div class="span6">
	
		<section class="box_color" onclick="location.href='/servicos/pagina'" style="cursor:pointer">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<div class="margem">
							<h4 class="">Lorem ipsum dolor sit amet</h4>
							<p class="">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
							<div class="wrapper">
								<ul class="social-icons icon-circle list-unstyled list-inline" style="margin-left:0px">
									<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
									<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
									<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
									<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
									<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
									<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="span3"">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:260px;width:340px"  class="w-100">
					</div>
				</div>
			<!--</div>-->
		</section>
	
	</div>
	
	<div class="span6">
	
		<section class="box_color" onclick="location.href='/servicos/pagina'" style="cursor:pointer">
			<!--<div class="card">-->
				<div class="row" >
					<div class="span3">
						<div class="margem">
							<h4 class="">Lorem ipsum dolor sit amet</h4>
							<p class="">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
							<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
							<div class="wrapper">
								<ul class="social-icons icon-circle list-unstyled list-inline" style="margin-left:0px">
									<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
									<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
									<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
									<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
									<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
									<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="span3"">
						<img src="https://cdn.megaleiloes.com.br/public/batches/16226/9ae1198fbfd4b93fbcadf8dd463c4432_320x240.jpg" style="height:260px;width:340px"  class="w-100">
					</div>
				</div>
			<!--</div>-->
		</section>
	
	</div>
	
</div>

</div>