<?=$this->headLink()->setStylesheet('css/application/servico.css');?>

<div id="content" class="container">

<div class="row">

	<?php echo $this->partial('application/partials/card_servico'); ?>
	
	<?php echo $this->partial('application/partials/card_servico'); ?>
	
</div>

<div class="row">

	<?php echo $this->partial('application/partials/card_servico'); ?>
	
	<?php echo $this->partial('application/partials/card_servico'); ?>
	
</div>

</div>