
<div id="content" class="container">

<div id="page-batch-detail">

<div class="row" style="margin-bottom: 20px;">
	<div class="span8">
		
		<h3 class="page-header" style="margin-bottom:10px">Titulo do Servico</h3>
		<div id="main-carousel" class="carousel slide">
			<ol class="carousel-indicators">
				<li data-target="#main-carousel" data-slide-to="0" class=""></li>
				<li data-target="#main-carousel" data-slide-to="1" class="active"></li>
			</ol>
			<div class="carousel-inner">
				<div class="item">
					<img src="https://cdn.megaleiloes.com.br/public/batches/16190/06dc17aa8f03e10b2ab8b356a18ddb89_670x380.jpg" 
					alt="Apartamento 51 m² - Jardim Umarizal - São Paulo - SP" style="width:100%">
				</div>
				<div class="item active">
					<img src="https://cdn.megaleiloes.com.br/public/batches/16190/9ba3b3647812c79fe956c54c924a6296_670x380.jpg" 
					alt="Apartamento 51 m² - Jardim Umarizal - São Paulo - SP" style="width:100%">
				</div>
			</div>
			<a class="carousel-control left" href="#main-carousel" data-slide="prev">‹</a>
			<a class="carousel-control right" href="#main-carousel" data-slide="next">›</a>
		</div>
		
		
		<div id="batch-description" class="box_color" style="line-height: 25px; margin-top:30px">
			<p class="margem">Matrícula nº 194.409 do 11º Cartório de Registro de Imóveis de São Paulo/SP - IMÓVEL: Apartamento nº 41 localizado no 4º andar do bloco BL-17, 
			integrante do empreendimento denominado Condomínio  Residencial Parque das Orquídeas, situado à Rua Jaracatiá nº 431 antigo s/nº, 
			Estrada de Campo Limpo nº 6.056 e Estrada dos Mirandas s/nº, no 29º Subdistrito-Santo Amaro, tendo o bloco acesso à Rua Jaracatiá através da Rua 3 
			(de circulação interna), possuindo a área útil de 51,715375 m2, a área comum de 29,180971 m2 já incluída a correspondente a uma vaga indeterminada no 
			estacionamento descoberto, e a área total de 80,896346 m2, correspondendo-lhe a fração ideal de 0,03434066% no terreno do condomínio. Consta no R.5 desta 
			matrícula que o imóvel objeto desta matrícula foi hipotecado à CAIXA ECONÔMICA FEDERAL - CEF. Consta no R.6 desta matrícula que nos autos da Ação de Prestação de 
			Contas, Processo nº 544/92, em trâmite na 32ª Vara Cível do Foro Central da Comarca de São Paulo/SP, requerida por MARCO ANTONIO BASSO e outro contra</p>                                                    
		</div>
		
		<h5 style="margin-top:20px"><b>Compartilhe:</b></h5>
		<div class="wrapper">
			<ul class="social-icons icon-circle list-unstyled list-inline" style="margin-left:0px">
				<li> <a href="#"><i class="fa fa-facebook"></i></a></li>
				<li> <a href="#"><i class="fa fa-pinterest"></i></a></li>
				<li> <a href="#"><i class="fa fa-google-plus"></i></a></li>
				<li> <a href="#"><i class="fa fa-twitter"></i></a></li>
				<li> <a href="#"><i class="fa fa-instagram"></i></a></li>
				<li> <a href="#"><i class="fa fa-youtube-square"></i></a></li>
			</ul>
		</div>

	</div>
	
	<div class="span4">
		
		<div class="label label-success marcador hidden-phone" >
			<span>Quero Saber Mais</span>
		</div>
		
		<div class="label label-success marcador visible-phone" style="margin-top:20px" >
			<span>Quero Saber Mais</span>
		</div>	
		
		<form class="form-vertical " id="contact-form" action="/contato" method="post">
			
			<label for="unidade" class="required"><b>Unidade</b></label>
			<!--select name="" id="unidade" style="width:320px">-->
			<select class="span3" name="" id="unidade">
			
				<option value="">Selecione uma Unidade</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
			
			</select>

			<label for="Contact_email" class="required"><b>Serviço</b></label>
			<!--select name="" id="unidade" style="width:320px">-->
			<select class="span3" name="" id="unidade">
			
				<option value="">Selecione um Serviço</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
			
			</select>
			
			<label for="Contact_email" class="required"><b>Onde conheceu o Serviço</b></label>
			<!--select name="" id="unidade" style="width:320px">-->
			<select class="span3" name="" id="unidade">
			
				<option value="">Selecione</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
				<option value="">2</option>
			
			</select>
			
			<label for="Contact_name" class="required"><b>Nome</b></label>
			<!--<input class="span3" name="Contact[name]" id="Contact_name" type="text" style="width:310px">-->
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>
			
			<label for="Contact_name" class="required"><b>Sobrenome</b></label>
			<!--<input class="span3" name="Contact[name]" id="Contact_name" type="text" style="width:310px">-->
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>
			
			<label for="Contact_name" class="required"><b>Email</b></label>
			<!--<input class="span3" name="Contact[name]" id="Contact_name" type="text" style="width:310px">-->
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>
			
			<label for="Contact_name" class="required"><b>Telefone</b></label>
			<!--<input class="span3" name="Contact[name]" id="Contact_name" type="text" style="width:310px">-->
			<input class="span3" name="Contact[name]" id="Contact_name" type="text">
			<span class="help-block error" id="Contact_name_em_" style="display: none"></span>
			
			<div class="form-actions">
				<input class="btn btn-primary" type="submit" name="yt1" value="Enviar">            
				<button class="btn" id="yw2" type="reset" name="yt2">Limpar</button>        
			</div>
			
		</form>
		
		
		<div class="label label-success" style="padding: 10px; font-size: 12px; display: block; margin-top:20px">
			<span>Atendemos</span>
		</div>	
		
		<div class="right-text px-3 box_color">
			<p class="card-text margem">
			
				Goiânia, Águas Lindas, Anápolis, Aparecida de Goiânia, Caldas Novas, Catalão, Ceres, Cidade Oriental, Cristalina, Formosa, Goianésia,
				Goiás, Goiatuba, Inhumas, Ipameri, Ipóra, Itaberaí, Itumbiara, Jaraguá, Jataí, Jussara, Luziânia, Mineiros, Minaçu, Morrinhos, Niquelândia,
				Novo Gama, Palmeiras de Goiás, Pirenópolis, Planaltina, Porangatu, Posse, Quirinópolis, Rio Verde, Santa Helena de Goiás, Santo Antônio do Descoberto,
				Trindade, Uruaçu, Valparaíso de Goiás.
			
			</p>
		</div>
		
		
	</div>
</div>



</div>

<div class="cards-list-alt" id="batches-list">

	<div class="top">
	
		<div><h3>Leilões Judiciais</h3></div>
		
		<hr class="divisão_hr">

		<!--<div class="summary">Exibindo leilões 1-32 de 283 resultados. Página 1 de 9.</div>

		<div class="pagination">
			<ul id="yw1" class="yiiPager">
				<li class="first disabled"><a href="/">&lt;&lt;</a></li>
				<li class="previous disabled"><a href="/">&lt;</a></li>
				<li class="num active"><a href="/">1</a></li>
				<li class="num"><a rel="next" href="/?pagina=2">2</a></li>
				<li class="num"><a href="/?pagina=3">3</a></li>
				<li class="num"><a href="/?pagina=4">4</a></li>
				<li class="num"><a href="/?pagina=5">5</a></li>
				<li class="num"><a href="/?pagina=6">6</a></li>
				<li class="num"><a href="/?pagina=7">7</a></li>
				<li class="num"><a href="/?pagina=8">8</a></li>
				<li class="num"><a href="/?pagina=9">9</a></li>
				<li class="next"><a rel="next" href="/?pagina=2">&gt;</a></li>
				<li class="last"><a href="/?pagina=9">&gt;&gt;</a></li>
			</ul>
		</div>-->

	</div>

	<div class="items">

		<ul class="thumbnails">
		
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
			
			<li class="item-row card success span3 ">
				<a class="type" href="https://www.megaleiloes.com.br/leiloes-judiciais">Judicial</a>    
				<a class="card-image" href="/leilao">
					<img width="320" height="240" src="https://cdn.megaleiloes.com.br/public/batches/16144/2bfda3a9802ecf3061b1261def5ec45a_320x240.jpg" 
					alt="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">
				</a>    
				<div class="card-status-numbers">
					<span><i class="icon-eye-open" data-toggle="tooltip" title="Visualizações"></i> 277</span>
					<span><i class="icon-legal" data-toggle="tooltip" title="Lances"></i> 0</span>
				</div>
				<a class="card-header" href="/leilao">
					<h2 class="title" title="50% de Imóvel Rural 7 alq. - Rio do Peixe - Garça - SP">50% de Imóvel Rural 7 alq. - Rio do Peixe -...</h2>
					<span class="instance">1ª praça</span>
					<span class="status">ABERTO PARA LANCES</span>
				</a>
				<button class="btn-add-auditorium btn-float hidden-phone" data-toggle="tooltip" title="" id="batch-16144" 
				data-type="batch" data-id="16144" data-auction="7017" data-original-title="Acompanhe a Disputa">
					<i class="icon icon-legal"></i>
				</button>
				<div class="card-body">
					<ul class="description">
						<li><span class="lih">Lote</span>J16144 / Lote 1</li>
						<li style="display: none!important;"><span class="lih">Categoria</span>
							<a href="https://www.megaleiloes.com.br/imoveis/imoveis-rurais/sp">Imóveis Rurais em SP</a>
						</li>
						<li><span class="lih">Localidade</span><a href="https://www.megaleiloes.com.br/imoveis/sp/garca">Garça, SP</a></li>
					</ul>
					<ul class="values">
						<li style="margin-top: 10px;"><span class="lih">1ª Praça</span>09/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 204.565,21</b></li>
						<li style="margin-top: 5px;"><span class="lih">2ª Praça</span>30/10/2017 às 10:00</li>
						<li><span class="lih"></span><b>R$ 122.739,13</b></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</li>
		
		</ul>

	</div>

</div>

</div>