<?= $this->doctype() ?>

<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?= $this->headTitle('Leilão MD - Admin')->setSeparator(' - ')->setAutoEscape(false) ?>
  
	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge, chrome=1')
		->appendHttpEquiv('cache-control', 'public')
		->appendName('description', 'Administrador')
		->appendName('author', 'Leilão MD')
		->appendName('copyright', 'Copyright © Leilão MD 2017 - 2020')
		->appendName('audience', 'all')
		->appendName('language', 'pt_br')
		->appendName('content-language', 'pt_br')
		->appendName('robots', 'index, follow')
		->appendName('application-name', 'Leilão MD')
		->appendName('theme-color', '#009cd7')
		->appendName('apple-mobile-web-app-title', 'Leilão MD')
	?>
	
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
		->prependStylesheet($this->basePath('css/sgs/main.css'))
		->prependStylesheet($this->basePath('adminlte/plugins/iCheck/square/blue.css'))
		->prependStylesheet($this->basePath('adminlte/dist/css/AdminLTE.min.css'))
		->prependStylesheet($this->basePath('adminlte/bower_components/Ionicons/css/ionicons.min.css'))
		->prependStylesheet($this->basePath('adminlte/bower_components/font-awesome/css/font-awesome.min.css'))
		->prependStylesheet($this->basePath('adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css'))
	?>


  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="login-page">

<?= $this->content ?>
	
	
<?= $this->headScript()
	->prependFile($this->basePath('adminlte/plugins/iCheck/icheck.min.js'))
	->prependFile($this->basePath('js/jquery.validate.min.js'))
	->prependFile($this->basePath('adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js'))
	->prependFile($this->basePath('adminlte/bower_components/jquery/dist/jquery.min.js'))
?>

<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>

</body>