<?= $this->doctype() ?>

<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?= $this->headTitle('Leilão MD - Admin')->setSeparator(' - ')->setAutoEscape(false) ?>
  
	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge, chrome=1')
		->appendHttpEquiv('cache-control', 'public')
		->appendName('description', 'Administrador')
		->appendName('author', 'Leilão MD')
		->appendName('copyright', 'Copyright © Leilão MD 2017 - 2020')
		->appendName('audience', 'all')
		->appendName('language', 'pt_br')
		->appendName('content-language', 'pt_br')
		->appendName('robots', 'index, follow')
		->appendName('application-name', 'Leilão MD')
		->appendName('theme-color', '#009cd7')
		->appendName('apple-mobile-web-app-title', 'Leilão MD')
	?>
	
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
		->prependStylesheet($this->basePath('adminlte/bower_components/font-awesome/css/font-awesome.min.css'))
		->prependStylesheet($this->basePath('adminlte/bower_components/Ionicons/css/ionicons.min.css'))
		->prependStylesheet($this->basePath('adminlte/dist/css/AdminLTE.min.css'))
		->prependStylesheet($this->basePath('adminlte/dist/css/skins/_all-skins.min.css'))
		->prependStylesheet($this->basePath('adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
		->prependStylesheet($this->basePath('adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css'))
	?>


  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="skin-blue sidebar-mini">

<div class="wrapper">

	<header class="main-header">
		<!-- Logo -->
		<a href="/admin" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><b>LMD</b></span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b>Leilão MD</b></span>
		</a>
		<!-- Header Navbar: style can be found in header.less -->
		<nav class="navbar navbar-static-top">
			<!-- Sidebar toggle button-->
			<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"></a>

			<div class="navbar-custom-menu">
				<ul class="nav navbar-nav">
					<li class="dropdown user user-menu">
					<a href="/admin">
						<span class="hidden-xs">Mike Dutra</span>
					</a>
					</li>
					<li>
						<a href="/admin" data-toggle="control-sidebar2"><i class="fa fa-power-off"></i></a>
					</li>
				</ul>
			</div>
		</nav>
	</header>
	
	
	<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="active sidebar-menu" data-widget="tree">
		<li class="">
          <a href="<?= $this->url('admin'); ?>">
            <i class="fa fa-circle-o"></i> <span>Home</span>
          </a>
        </li>
        <li class="active">
          <a href="<?= $this->url('grupo', ['action'=>'criar']); ?>">
            <i class="fa fa-circle-o"></i> <span>Criar Grupo</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  
  
  
  <div class="content-wrapper">
  
	<?= $this->content ?>
  
  </div>
  
  

</div>
<!-- ./wrapper -->

	
	
<?= $this->headScript()
	->prependFile($this->basePath('js/sgs/funcoes.js'))
	->prependFile($this->basePath('js/jquery.validate.min.js'))
	->prependFile($this->basePath('adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
	->prependFile($this->basePath('adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js'))
	->prependFile($this->basePath('adminlte/bower_components/jquery-ui/jquery-ui.min.js'))
	->prependFile($this->basePath('adminlte/bower_components/jquery/dist/jquery.min.js'))
?>

</body>
















