<div id="content" class="container">
	
	<div class="row">
	
		<div class="span3">
		
			<div class="row">
			
				<div class="span3 text-center box_color">
			
					<img src="https://www.zukerman.com.br/imagens/img-profile.png" style="padding:15px">
				
				</div>
			
			</div>			
		 
			<div class="label label-padrao marcador marcador_margem_user" style="margin-top:20px">
				<span>Minha Conta</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Dados Cadastrais</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Meus Documentos</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Alteração de Senha</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Minha Habilitação</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Favoritos</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Meus Lances</span>
			</div>
			
			<div class="label label-padrao marcador marcador_margem_user">
				<span>Negocios Fechados</span>
			</div>
		
		</div>
	
	</div>

</div>