<div id="content" class="container">


	<div class="row" style="margin-top:0px;">

		<div class="span2 text-center " style="">
			<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 4;" face="arial">
			<b><span style="cursor: pointer;" onclick="altera_pgr('trabalhe_conosco')">TRABALHE CONOSCO</span></b></font></div>
		</div>

		<div class="span2 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 4;" face="arial">
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_aprendiz')">PROGRAMA APRENDIZ</span></b></font></div>
		</div>

		<div class="span2 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 4;" face="arial">
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_estagio')">PROGRAMA ESTAGIO</span></b></font></div>
		</div>

		<div class="span2 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 4;" face="arial">
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_treinee')">PROGRAMA TREINEE</span></b></font></div>
		</div>

		<div class="span2 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 4;" face="arial">
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_integral')">PROGRAMA INTEGRAL</span></b></font></div>
		</div>

		<div class="span2 text-center " style="">
		<div class="fundo_classes2" style=""><font class="cor_letra" style="font-size:10px; line-height: 4;" face="arial">
			<b><span style="cursor: pointer;" onclick="altera_pgr('pgr_tercerizado')">PROGRAMA TERCERIZADO</span></b></font></div>
		</div>

	</div>
	
	
	<div class="row " style="margin-top:30px;">
    
        <div class="span4">
            
			<div class="box_color margem text-center" style="margin-top:0PX;">
				<p style="font-size:14px;">
					<b>UNIVERSIDADE COORPORATIVA</b>
				</p>
			</div>
            
			<div class="box_color margem" style="margin-top:5px; height: 509px;">
				<p align="justify" style="color:#003862; padding-top:0px;"><font face="arial" style="font-size:14px"> 
					
					O Grupo Dutra investe na retenção e manutenção de pessoas preparadas para o crescimento e
					que combinem potencial, desempenho e interesse na oportunidade de viver desafios de
					diferentes naturezas. Por esse motivo o Grupo Dutra criou a UCD sua Universidade Corporativa
					Dutra, onde oferecemos oportunidades de formação e capacitação, centralizadas no Sistema
					de Desenvolvimento Profissional (SDP), para garantir que os trabalhadores estejam sempre
					qualificados. Seu principal objetivo é identificar as necessidades de treinamento e viabilizá-los,
					executando assim, o desenvolvimento das habilidades dos trabalhadores para o pleno
					exercício de suas funções. Além de atividades realizadas em parceria com instituições
					profissionalizantes, tais como o SENAG, SENAI, FGV, IBCA, IBCI, IBCV, IBCE.
					
				</font></p>
				
				<p align="justify" style="color:#003862; padding-top:0px;">
					<font face="arial" style="font-size:14px">
						
						Somente uma empresa que tem um modelo único de gestão consegue manter tantas
						empresas e pessoas num constante processo de crescimento. Dar total condição para o
						desenvolvimento e capacitação é uma das prioridades do nosso grupo junto aos seus
						colaboradores e parceiros.
						
					</font>
				</p>
				
			</div>
            
        </div>
        
        <div id="trabalhe_conosco" class="span8 box_color" style="height: 575px;">
            
                <div class="box_color margem" style="margin-top:0PX;">
                    <p style="font-size:14px;">
                        <b>TRABALHE CONOSCO</b>
                    </p>
				</div>
            
                <div class="box_color margem" style="margin-top:5px; ">
            
                    <p style="color:#003862;; padding-top:0px;">
						<font face="arial" style="font-size:14px"> 
					
						As pessoas são a chave para o sucesso do nosso negócio. Nós somos apaixonados por quem faz e
						acreditamos que os maiores talentos nascem da paixão por fazer. Se você é um apaixonado por fazer,
						venha fazer parte desta equipe que acredita que com paixão podemos transformar a realidade.
						Somos um grupo que valoriza o capital humano, que acredita que cada um agrega valor ao sucesso da
						organização e que pessoas felizes geram resultados felizes.
						
						</font>
					</p>
                    
                    <p style="color:#003862;; padding-top:0px;">
						<font face="arial" style="font-size:14px"> 
						
						Nossa cultura é diferenciada, pois é formada pela inovação nos processos e projetos, pela agilidade no
						“fazer acontecer” e pelo foco nos nossos clientes, internos e externos.
						
						</font>
					</p>
					
					<p style="color:#003862;; padding-top:0px;">
						<font face="arial" style="font-size:14px"> 
						
							Estamos comprometidos em criar experiências que reforcem a capacidade de cada um, visando o
							desenvolvimento humano e profissional de nossos colaboradores, por meio de recrutamentos internos,
							treinamentos e outras oportunidades.
					
					
						</font>
					</p>
				</div>
		</div>
        

</div>